### ISSUE TITLE
docs: create and document Vite templates

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5260] opened 2021-10-07 13:42 UTC
# 🙋 Documentation Request

Expand support beyond Webpack by creating a Vite template for FAST and add a corresponding page to our integrations documentation.

See https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by huynhicode** [comment] 2022-02-02 18:08
Closing this issue as it is a duplicate of https://github.com/microsoft/fast/issues/5409.

**Closed** 2022-02-02 18:09 UTC
Labels: closed:duplicate, community:help-wanted, docs:article, status:under-consideration, area:site, community:noteworthy
