### ISSUE TITLE
fix: SSL Cert error in fast.design domain

### ISSUE THREAD

**Issue by omar2205** [microsoft/fast#6751] opened 2023-05-27 06:17 UTC
# 🐛 Bug Report

When visiting fast.design (Not www.fast.design) I get `NET::ERR_CERT_DATE_INVALID`

More info:

```
Subject: fast.design

Issuer: Microsoft RSA TLS CA 02

Expires on: Nov 13, 2022

Current date: May 27, 2023
```

**Comment by huynhicode** [comment] 2023-09-03 17:50
This is a duplicate of [6524](https://github.com/microsoft/fast/issues/6524).

**Closed** 2023-10-09 21:11 UTC
Labels: status:triage
