### ISSUE TITLE
Non-unique ids when rendering multiple TextField components

### ISSUE THREAD

**Issue by brianchristopherbrady** [microsoft/fast#6962] opened 2024-05-16 18:31 UTC
# 🐛 Bug Report

Accessibility warnings for non-unique id attributes when rendering multiple instances of the FASTTextField component.

## 💻 Repro or Code Sample

Create multiple instances of the FASTTextField component in a single page and run an accessibility audit or tool like Accessibility Insights.

## 🤔 Expected Behavior

Each instance of the FASTTextField component should have a unique id for its internal control element to pass accessibility audits.

## 😯 Current Behavior

Accessibility warnings for non-unique id attributes are shown when rendering multiple instances of the FASTTextField component.

## 💁 Possible Solution

Consider removing the static id from the internal control element or make it unique for each instance.

## 🔦 Context

This issue causes accessibility warnings, which can affect the accessibility compliance of the application.

## 🌍 Your Environment

* OS & Device: Windows,  PC
* Browser Chrome
* Version 124.0.6367.93 (Official Build) (64-bit)

**Comment by chrisdholt** [comment] 2024-05-16 19:14
ID's are unique to each document instance - ID's within the shadow DOM are considered unique. Closing this as "by design".

**Closed by chrisdholt** 2024-05-16 19:14 UTC
Labels: status:triage
