### ISSUE TITLE
Select dropdown menu items are not getting resized upon Hover

### ISSUE THREAD

**Issue by saichiravuri** [microsoft/fast#5558] opened 2022-02-03 06:07 UTC
## 🤔 Expected Behavior

- When hovering over Select menu items, text should get resized to 60pt

## 😯 Current Behavior

- When hovering over Select menu items, text not getting resized

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by EisenbergEffect** [comment] 2022-02-03 14:52
@saichiravuri Can you provide a bit more information on this? In particular, why should the select menu items have the specific text style applied to change the font size to 60pt on hover?

**Comment by saichiravuri** [comment] 2022-02-04 05:11
@EisenbergEffect We have received an accesibility bug on this behavior, I checked all other fast select components too they are also having the same behavior.

"Expected Result:
When hovering over '<my select>' menu items, text should get resized to 60pt
 
User Impact:
Low vision user will face difficulties as they will not be able to see the text of menu items"

Feel free to close if this is not really universal standard to follow..

**Comment by EisenbergEffect** [comment] 2022-02-04 13:27
I'll defer to @chrisdholt

**Comment by chrisdholt** [comment] 2022-02-04 19:02
Thanks @saichiravuri - I'm primarily curious *which* assistive technology tool this is. Is it a built in for Mac? Is it an extension? I just need more detail to be able to reproduce this and understand if the issue is with our approach or if it's in the tool itself. Just from the bug itself it seems more related to work the tool may be doing to magnify the UI itself and I'm not sure that's something that would fall to us. With that said, we're happy to investigate and provide a solid answer, we just need to understand *what is being tested* here using *what tool*. Thanks!

**Comment by chrisdholt** [comment] 2022-04-03 04:05
Closing this out as we don't have enough information regarding which a11y feature this is in regards to on Mac. Either way, we aren't able to map to explicit a11y features, so my hunch is this that this is an issue with the tooling. If you get more information, feel free to reopen.

**Closed by chrisdholt** 2022-04-03 04:05 UTC
Labels: status:needs-information, area:fast-foundation, area:fast-components, community:question
