### ISSUE TITLE
Blazor - Fast menu item does not appear on the top of fast-card

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4704] opened 2021-05-12 03:45 UTC
I have a Dropdown button Razor component that is implemented as follows...

```
<div class="pi-ddb">
        <fast-button appearance="@Appearance=" @onclick="(cargs) => OnClickHandler(cargs)">
                @Title
                <i class="@Caret" slot="end"></i>
        </fast-button>

        @if (showMenu)
        {
                <div class="pi-ddb-rmenu">
                    <fast-menu>
                        @ChildContent
                    </fast-menu>
                </div>
        }
</div>
```

```
<fast-menu-item @onclick="OnMenuItemClickInternalAsync" class="pi-ddb-item-link">
    @ChildContent
</fast-menu-item>
```

css

```
.pi-ddb {
    position: relative;
    display: inline-block;
}

.pi-ddb-rmenu {
    position: absolute;
    min-width: 220px;
    right: 0;
    z-index: 1;
    margin-top: 10px;
}
```

```
/*Mouse down (hover & active)*/
.pi-ddb-item-link:hover:active {
    color: var(--accent-foreground-active);
    background-color: var(--neutral-fill-active);
}

/* Mouse hover */
.pi-ddb-item-link:hover {
    color: var(--accent-foreground-hover);
    background-color: var(--neutral-fill-hover);
}
```

Now if I add the Button Dropdown inside the fast-card, it hides the menu. 

I tried changing the z-index to be 999 for .pi-ddb-rmenu  (fast-menu) but still it does not show the menu

![image](https://user-images.githubusercontent.com/13166236/117914948-1c54ec00-b299-11eb-94f5-534ebd239a55.png)

The only way i can make the fast-menu visible is by increasing the height of fast-card as shown below...

![image](https://user-images.githubusercontent.com/13166236/117915192-9f764200-b299-11eb-92a1-54519c2aad11.png)

How do I make sure the fast-menu and fast-menu-item are always displayed on the top of all other components ?

**Comment by scomea** [comment] 2021-05-12 06:14
You could wrap your menu in an anchored-region that can place it as a fixed element (ie. breaks it out of parent containers) and positions it next to the element you "anchor" it to.   You may need to set some z-indexes if you have other "position: fixed" elements in your scenario.  The auto update mode setting keeps the fixed menu next to it's anchor as you scroll/resize. 

Something like this might work (guessing at the menu behavior you want for settings):

  `@if (showMenu)
        {
                <fast-anchored-region
                        anchor="<The id of the button that spawned me>"
                        fixed-placement="true"
                        vertical-positioning-mode="dynamic"
                        vertical-default-position="bottom"
                        vertical-scaling="content"
                       horizontal-positioning-mode="dynamic"
                       horizontal-default-position="left"
                       horizontal-scaling="content"
                       horizontal-inset="true"
                       auto-update-mode="auto"
                  >
                    <fast-menu>
                        @ChildContent
                    </fast-menu>
                </fast-anchored-region>
        }`

**Comment by ameyasubhedar** [comment] 2021-05-12 20:02
@scomea, using the anchored-region gives me the same issue... here is my sample code

```
 <fast-button id="@Id" appearance="@Appearance=" @onclick="(cargs) => OnClickHandler(cargs)">
        @Title
        <i class="@Caret" slot="end"></i>
    </fast-button>

    @if (showMenu)
    {
         @* https://github.com/microsoft/fast/issues/4704 *@
        <fast-anchored-region anchor="@Id"
                          fixed-placement="@true"
                          vertical-positioning-mode="dynamic"
                          vertical-default-position="bottom"
                          vertical-scaling="content"
                          horizontal-positioning-mode="dynamic"
                          horizontal-default-position="@HorizontalPosition"
                          horizontal-scaling="content"
                          horizontal-inset="true"
                          auto-update-mode="auto"  
                          style="margin-top:10px;">
            <fast-menu>
                @ChildContent
            </fast-menu>
        </fast-anchored-region>
    }
```

used inside the fast-card the anchored-region as a fixed element is still hidden by the card.'

![image](https://user-images.githubusercontent.com/13166236/118036606-a183e380-b321-11eb-8f36-c61f5846184c.png)

Another issue is that margin-top is not honored by the anchored region. If I add style="margin-top:10px;" to the  fast-anchored-region it still starts immediately below the spawning button

**Comment by ameyasubhedar** [comment] 2021-05-12 20:16
You can reproduce the issue in the fast.design website directly !

```
<fast-card style="height:150px">          
        <fast-button id="abc">Button</fast-button>
        <fast-anchored-region anchor="abc" fixed-placement vertical-positioning-mode="dynamic" vertical-scaling="content" horizontal-positioning-mode="dynamic" horizontal-scaling="content" horizontal-inset auto-update-mode="auto" vertical-default-position="bottom">
            <fast-menu>
                <fast-menu-item>Menu 1</fast-menu-item>
                <fast-menu-item>Menu 2</fast-menu-item>
                <fast-menu-item>Menu 3</fast-menu-item>
                <fast-menu-item>Menu 4</fast-menu-item>
                <fast-menu-item>Menu 5</fast-menu-item>
            </fast-menu>
        </fast-anchored-region>    
</fast-card>
```

![image](https://user-images.githubusercontent.com/13166236/118038548-1bb56780-b324-11eb-8dd2-14659473232a.png)

**Comment by scomea** [comment] 2021-05-12 23:09
> Another issue is that margin-top is not honored by the anchored region. If I add style="margin-top:10px;" to the fast-anchored-region it still starts immediately below the spawning button

This is by design.  If you want a margin on the menu set it on the menu element and not the region.

**Comment by scomea** [comment] 2021-05-12 23:11
The clipping is because the card styling has "contains: content" set which helps with perf in some scenarios but limits rendering outside the component.  You can override that style with another value ("none" or maybe "size") so your menu can render outside.

**Comment by scomea** [comment] 2021-05-12 23:13
We may need to consider if "contains: content" is the best default setting, but the workaround is easy.

**Comment by ameyasubhedar** [comment] 2021-05-13 00:18
@scomea, I think we trying to bypass the issue by not setting contain:content.  But may be you can help explain this better.

Both contain:size and contain:none has side effects on the card contents.

To show this here is an example with multiple cards

**Case 1: fast-card -> style="contain:content"**
![image](https://user-images.githubusercontent.com/13166236/118058968-457e8680-b344-11eb-9143-b101a6569c3f.png)

Case 1 Issue - Menu Is clipped (this should not happen, there should to be a property that can tell the rendering engine to not 
 clip the menu, for e.g. NoClip or use z-index)

**Case 2:  fast-card -> style="contain:none"**
![image](https://user-images.githubusercontent.com/13166236/118059168-b45bdf80-b344-11eb-8549-a584ff444346.png)

Case 2 Issue: Menu is shown correctly, but now the contents of the card are not positioned correctly. For e.g. the margin defined on the div inside the card is ignored. You can see the button 'Action' and title 'Test Client 1' start at top.

**Case 3:  fast-card -> style="contain:size"**
![image](https://user-images.githubusercontent.com/13166236/118059533-9b076300-b345-11eb-8f6f-7092a7d1109f.png)

Case 3 Issue: Menu is shown correctly, but Both card overlaps with each other. So size is clearly not an option !

I am not sure, what approach to take to have a consistent behavior for the menus inside the card. Looks like a bug to me.

**Comment by scomea** [comment] 2021-05-13 01:40
> @scomea, I think we trying to bypass the issue by not setting contain:content. But may be you can help explain this better.

https://developer.mozilla.org/en-US/docs/Web/CSS/contain 

If the scenario is that a descendant of the card renders outside of the bounds of the card, which is exactly what the menu is doing, then card can't have a css contain value of "content" or "paint" because "if a descendant overflows the containing element's bounds, then that descendant will be clipped to the containing element's border-box."  The "size" setting doesn't work because the are sized based on their content. So I think it has to be either "none" or maybe "layout".   I would expect the value of "contain" to vary for different scenarios. 

> 
> To show this here is an example with multiple cards

I understand why "content" and "size" don't work work for you ("size" wasn't what I thought it was), but the "none" one I'm confused about. It should essentially behave as "contain" is not set at all and regular css layout rules should apply.  I was able to set margins and padding inside a card based on your markup above.

> I am not sure, what approach to take to have a consistent behavior for the menus inside the card. Looks like a bug to me.

I'd try to get your scenario working with "none" (If regular css layout doesn't work with "contain" set to "none" that would probably be a some kind of platform bug).  After that if you can turn on some value for containment without causing an issue then take it and whatever perf boost it gives you.  If you decide your cards must have a restrictive setting for "contain" then you need to account for that by not having flyouts within a card that render outside of its boundaries.  You could do with a visual design change or structure your app such that the flyout generated when you click inside the card isn't actually a child of the card in the dom.

**Comment by scomea** [comment] 2021-05-13 05:31
I do think that at a minimum we do need to talk about this somewhere in the docs so devs understand that a default value for "contain" has been set and its consequences.  I doubt you'll be the first to encounter clipping due to it. We may want to reconsider if "content" is the right default  @chrisdholt?

**Comment by chrisdholt** [comment] 2021-09-16 07:09
I'm going to close this in coordination of closing #4790 for the reasons outlined in this [comment](https://github.com/microsoft/fast/issues/4790#issuecomment-891498567). The addition of the `<popup>` element as outlined in [Open UI](https://github.com/openui/open-ui/blob/main/research/src/pages/popup/popup.research.explainer.mdx) should better enable the ability to "break out" of containers. Once available we'll be looking to leverage this right away.

**Closed by chrisdholt** 2021-09-16 07:09 UTC
Labels: improvement, status:needs-investigation, area:fast-components, community:request
