### ISSUE TITLE
Slot spacing incorrect for fast-button

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4830] opened 2021-06-04 17:08 UTC
Define a simple razor button component

**Definition Button.razor**
```
  <fast-button id="@Id" type="button">
      @ChildContent
  </fast-button>
```

**Usage**
```
<Button>
   <i class="fas fa-edit" slot="start" />
   Title
</Button>

```

**Generated HTML**
```
<fast-button type="button" appearance="neutral">
          <i class="fas fa-edit" slot="start" />
           Title
</fast-button>
```

**Issue**
![image](https://user-images.githubusercontent.com/13166236/120837348-6ee19b00-c51b-11eb-8263-d7266015de6c.png)

Notice the start slot and title are right next to each other without any spacing !

How do I ensure spacing between the slots ?

**Comment by ameyasubhedar** [comment] 2021-06-04 17:58
I think fast foundation needs to expose a CSS custom variable --slot-spacing that apps can configure and this slot spacing should be consistent across all the fast components e.g. button, menu etc..

**Comment by chrisdholt** [comment] 2021-06-04 20:17
Interesting that this is what you're seeing. When I open the component explorer, I'm able to see the space being applied as expected.

![image](https://user-images.githubusercontent.com/13071055/120858069-14563800-c537-11eb-8174-596805938fc6.png)

What happens if the `<i>` is not a self closing element (I don't believe it is)? Alternatively, could you put together a simple repro for blazor to see if this specific to that use case?

**Comment by ameyasubhedar** [comment] 2021-06-07 15:04
@chrisholt, here is the Blazor web assembly [repo ](https://github.com/ameyasubhedar/Blazor-Fast-SlotSpacing
)that shows the issue. 

Click on the Counter Menu and you will see the FastButton with start and end slot and both does not have the spacing applied. 

**Component FastButton.razor**
```
<fast-button type="button" @onclick="@OnClick">
    @ChildContent
</fast-button>

@code {

    [Parameter]
    public RenderFragment ChildContent { get; set; }

    [Parameter]
    public EventCallback<MouseEventArgs> OnClick { get; set; }
}
```

**Usage**
```
<div style="display:flex; justify-content:center;align-items:center">
    <FastButton OnClick="IncrementCount">
        <i class="oi oi-plus" slot="start"></i>
        Increment
    </FastButton>

    <span class="mr-5">
    </span>

    <FastButton OnClick="DecrementCount">
        <i class="oi oi-minus" slot="end"></i>
        Decrement
    </FastButton>
</div>
```

**Issue**
![image](https://user-images.githubusercontent.com/13166236/121040494-cc1d5c80-c766-11eb-988d-92d074ac0723.png)

**Comment by ameyasubhedar** [comment] 2021-06-08 18:25
@chrisdholt, I am facing the same issues while using menu and tree list. the slot spacing is not honored.

Can you please check the [repo ](https://github.com/ameyasubhedar/Blazor-Fast-SlotSpacing)and let me know if this specific to Blazor and anything that apps needs to configure for this to work.

![image](https://user-images.githubusercontent.com/13166236/121237576-0b71a900-c84c-11eb-8332-b13b10b60059.png)

**Comment by chrisdholt** [comment] 2021-06-08 18:29
> @chrisdholt, I am facing the same issues while using menu and tree list. the slot spacing is not honored.
> 
> Can you please check the [repo ](https://github.com/ameyasubhedar/Blazor-Fast-SlotSpacing)and let me know if this specific to Blazor and anything that apps needs to configure for this to work.
> 
> ![image](https://user-images.githubusercontent.com/13166236/121237576-0b71a900-c84c-11eb-8332-b13b10b60059.png)

This does seem to hint at this being specific to Blazor. Adding @nicholasrice and @EisenbergEffect to see if either of them have initial ideas on what might be happening here.

**Comment by nicholasrice** [comment] 2021-06-15 16:20
This is caused by https://github.com/microsoft/fast/issues/4692. Closing as a duplicate.

**Closed by nicholasrice** 2021-06-15 16:20 UTC
Labels: community:request, status:needs-information
