### ISSUE TITLE
Select accessibility issue with screen reader

### ISSUE THREAD

**Issue by vaudy** [microsoft/fast#4514] opened 2021-03-30 14:17 UTC
**Describe the bug; what happened?**
When using a screen reader for accessibility, the navigation over options using they keyboard arrow didn't tell on which option we are.

**What are the steps to reproduce the issue?**

1. Activate accessibility on you computer
2. focus a select component
3. Press space to open it
4. Use the arrow key to navigate over an option
5. No voice over is telling me which option im on.

**What behavior did you expect?**
I would like to have the same kind of feedback the menu and menu-item offers. A bit like a native select does

* OS & Device: MacOS
* Browser Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox
* Version lastest

**Is there any additional context?**

**Comment by vaudy** [comment] 2021-03-30 14:24
Here's an example on the expected behaviours thanks https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by chrisdholt** [comment] 2021-03-30 16:30
Thanks for the issue @vaudy - I do repo the issue on options as I'm on a Mac, though I will say that VoiceOver is notoriously unreliable as a screen reader. We've built to the W3C ARIA specification for a select only combobox, which does seem to be recognized. I think our first steps here is to see if this repro's on other assistive technology which is aligned to the current ARIA 1.2 spec.

**Comment by chrisdholt** [comment] 2021-08-03 03:58
Hey @Vaudy, we just did a fairly robust accessibility pass on the components and this did not repro across our AT testing matrix. With that said, Voiceover does have issues with regard to accessibility. An example is that implementations of a `listbox` are read back as though it is a tree view with tree items with Voiceover. Given our testers did not flag this for other AT (Narrator, NVDA as examples) I'm going to close this as it's specific to Voiceover and we have built to the ARIA 1.2 specification for a single select combobox which is quite different from the 1.1 implementation. Accessibility is a big issue for us as well, if you find that there are still issues with other AT, we're happy to dig in with our accessibility testing team. Alternatively, we can also attempt to open a bug on Apple, though we can't ensure that it will produce any action. Since we don't have any way to single out Voiceover and we've built to the spec, I'm going to close this as non-actionable for now. Thanks!

**Closed by chrisdholt** 2021-08-03 03:58 UTC
Labels: area:fast-components, area:fast-foundation, compliance:a11y, status:needs-investigation

**Comment by daviddossett** [comment] 2021-09-28 04:06
I'm running into a similar issue where we're getting flagged on the Select component not announcing values as users arrow through the options. The testing team found the issue using NVDA and JAWS. I also reproduced it on VoiceOver, however I understand from reading the thread above that it's not considered an issue.

I did notice that the FAST Combobox showcased [here](https://explore.fast.design/components/fast-combobox) doesn't seem to have the same issue. It announces values (on VoiceOver too) as expected. Is there a known reason why the two would behave differently? I thought it was the same listbox under the hood.

**Comment by chrisdholt** [comment] 2021-09-28 04:11
> I'm running into a similar issue where we're getting flagged on the Select component not announcing values as users arrow through the options. The testing team found the issue using NVDA and JAWS. I also reproduced it on VoiceOver, however I understand from reading the thread above that it's not considered an issue.
> 
> I did notice that the FAST Combobox showcased [here](https://explore.fast.design/components/fast-combobox) doesn't seem to have the same issue. It announces values (on VoiceOver too) as expected. Is there a known reason why the two would behave differently? I thought it was the same listbox under the hood.

It could be an issue, I think we'll need to dig in on this in isolation. The odd thing about this is that Select is essentially an implementation of a single select combobox and built according to the ARIA practices spec (note: not the example!). It *could* be related to something we are already tracking, but if you can open a new issue we'll take a look!

**Comment by daviddossett** [comment] 2021-09-28 04:26
Thanks for the quick response—will do. 

FWIW we're still on fast-foundation v1. Not sure if that has an impact here.

**Comment by chrisdholt** [comment] 2021-09-28 04:27
> Thanks for the quick response—will do.
> 
> FWIW we're still on fast-foundation v1. Not sure if that has an impact here.

I don’t think we made significant enough changes in this regard to be the underlying cause of this.
