### ISSUE TITLE
fix: empty value attribute in fast option when used in fast select triggers the use of textContent

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4663] opened 2021-05-03 23:30 UTC
# 🐛 Bug Report

When `<fast-option>` has `value` this should always be used when emitting changes. This is not the case when value is an empty string, the `<fast-select>` will use the `textContent` instead, which may be different.

## 💻 Repro or Code Sample

Create a `<fast-select>` with contained `<fast-option>` and attempt to change from a value with text to a value with empty text.

Example:
```
<fast-select>
    <fast-option value="">Default</fast-option>
    <fast-option value="foo">Foo</fast-option>
</fast-select>
```

Select "Foo", then select "Default".

## 🤔 Expected Behavior

With the example above, you should receive the value "" as the event value.

## 😯 Current Behavior

With the example above, you will receive the value "Default" instead of "" as the event value.

## 💁 Possible Solution

There is a general "falsey" check for the `value` attribute, this should be changed to a `typeof` check for `"string"`.

## 🔦 Context

In the case where no value is desired as having been initially set, an empty option should be possible.

**Comment by ben-girardet** [comment] 2021-09-03 06:24
Just came across this same situation. Any news on this issue ?

**Comment by radium-v** [comment] 2022-04-21 23:30
I can't reproduce the issue on the current release.

**Comment by chrisdholt** [comment] 2022-04-22 00:17
> I can't reproduce the issue on the current release.

closing given this investigation - if this is still an issue feel free to reopen. Thanks!

**Closed by chrisdholt** 2022-04-22 00:17 UTC
Labels: bug, status:needs-investigation, area:fast-components
