### ISSUE TITLE
Fast Select Dropdown does not break out of parent component

### ISSUE THREAD

**Issue by apsthisdev** [microsoft/fast#4791] opened 2021-05-27 07:02 UTC
fast-select with options does not break out and options are hidden. In almost all the practical use cases the select component will be used inside the parent component

To show the issue, i just added a grid control and added fast select inside a grid cell.

```
<fast-data-grid grid-template-columns="1fr 1fr 1fr">
    <fast-data-grid-row>
        <fast-data-grid-cell grid-column="1">
            Name
        </fast-data-grid-cell>
        <fast-data-grid-cell grid-column="2">
            <fast-select>
                <fast-option value="1" style="z-index:1">Option 1</fast-option>
                <fast-option value="2">Option 2</fast-option>
                <fast-option value="3">Option 3</fast-option>
            </fast-select>
        </fast-data-grid-cell>
        <fast-data-grid-cell grid-column="3">
            Info
        </fast-data-grid-cell>
    </fast-data-grid-row>
</fast-data-grid>
```

![image](https://user-images.githubusercontent.com/13166236/119780308-80250a80-be7e-11eb-8f41-8f507c66de12.png)

Expected Behavior:
The Fast Select dropdown should break out of parent control and not hidden by default.

**Comment by EisenbergEffect** [comment] 2021-06-21 17:26
Ping @scomea

**Comment by chrisdholt** [comment] 2021-06-21 17:55
@scomea may not chime in right away as he's taking some time off this week. I'll do my best to articulate some of the problem and our long term solution. I think the overall problem is the same one explained a bit as part of this [comment](https://github.com/microsoft/fast/issues/2235#issuecomment-530649486). One thing that may be contributing to this behavior in the WC select as well is that I don't believe it's making use of `anchored-region`.

There are two explainers that could each independently help solve this problem for us in the long term:
1. [Popup](https://open-ui.org/components/popup.research.explainer) - This will help formalize the expected behavior via a new HTML element (`<popup>`).
2. Improving the customization of form controls, specifically `<select>` - Once available we'll likely use a progressive-enhancement model to use this control when available. 

In the short term, I think it'll be important to get @radium-v's thoughts here on whether using Anchored Region is a good short term fix, and what the potential implications are of doing that. Alternatively, I think some of this is due to CSS, most often with positioning, which often means a very tightly coupled relationship between parent/child. This makes it difficult for us to come up with a universal, "it just works" approach for every element. The two long term solutions will help solve that for good I believe. In the meantime, I think the question becomes, "What's the right short term solution and how much coverage can we get?"

**Comment by scomea** [comment] 2021-06-24 21:21
Yes, anchored region should be able to give us some options here.  I've been meaning to start a branch to test that out.

**Comment by atmgrifter00** [comment] 2021-12-22 22:40
@chrisdholt, I expect the fact that the fast-combobox dropdown menu is cut off when it is used as the column template for a fast-datagrid has the same root issue you're describing (making sure I shouldn't file a separate issue). If it is the same issue, as I expect it is, can you elaborate on how you would use the `anchored-region` to solve the problem in the short term?

**Comment by scomea** [comment] 2021-12-22 23:57
Anchored-region is able to position itself relative to its anchor in either a "fixed" or "absolute" positioning mode.  Fixed positioning is useful precisely because it allows the flyout to break out of parent containers more easily.

**Comment by atmgrifter00** [comment] 2022-01-01 16:43
I think I should have been a bit more specific in my ask. So if I, as a current user of the FAST components (in particular the FluentUI/Blazor widget set), want to be able to have the fast-combobox (i.e. FluentComboBox) have it's dropdown menu break out of its owner's bounds, is there a way for me to use the FluentAnchoredRegion to do so? I wouldn't expect that there is, as the div that is responsible for this ([the popup](https://github.com/microsoft/fast/blob/b816a09d0cf393567396e3f5a8e06312798dc05e/packages/web-components/fast-foundation/src/combobox/combobox.template.ts#L57)) is tucked away in the template of the fast-combobox.

I feel I may be missing something, and I apologize if I'm being obtuse.

**Comment by scomea** [comment] 2022-01-02 19:09
> My current read on this is, as a consumer of FAST (or the FluentUI/Blazor-based widgets), that there is nothing I can do to resolve this at the moment.

I wouldn't say "nothing", just not some easy out of the box solution using select as it is currently.  You'd need to 'roll your own' to some extent.

**Comment by chrisdholt** [comment] 2022-01-02 19:58
We are tracking this work on Select, it’s simply behind some accessibility work that’s currently in process.

**Comment by atmgrifter00** [comment] 2022-01-02 19:59
Would you expect to do the same work on the Combobox at the same time?

**Comment by chrisdholt** [comment] 2022-01-02 20:01
> Would you expect to do the same work on the Combobox at the same time?

Yes, these are closely aligned and we’d expect to do both simultaneously. Hopefully it’s not too far off.

**Comment by SethDonohue** [comment] 2022-01-03 18:47
I had a few attempts at this without it being major changes, but I think it's best if scomea or someone else took a look at it!

**Comment by thinkbig1979** [comment] 2022-10-12 13:34
> @chrisdholt , Any update on the timeline for a fix ? Almost an year since the original issues was opened! This does impact a lot of basic use cases for simple selections.
> 
> The FluentUI fast wrappers for Blazor also has the same issue.

Also very interested in a fix. In the case of our application, the dropdown sits on a card that can be one of many cards in the view. One would expect the dropdown to just open over the top of the other elements on the page, including its parent element, but it just runs into the edge of the card and does not expand any further. This can be clearly seen in the component explorer on the fast.design page as well by resizing the container that the select component is in. As it stands, this is effectively preventing us from using the select dropdown.

**Comment by scomea** [comment] 2022-10-12 14:46
I have a prototype branch that hooks up select to a refactored anchored-region positioning class here -https://github.com/microsoft/fast/tree/users/scomea/anchor-region-refactor

That would be able to escape parent containers much more effectively.

**Comment by chrisdholt** [comment] 2022-10-12 23:53
> > @chrisdholt , Any update on the timeline for a fix ? Almost an year since the original issues was opened! This does impact a lot of basic use cases for simple selections.
> > The FluentUI fast wrappers for Blazor also has the same issue.
> 
> Also very interested in a fix. In the case of our application, the dropdown sits on a card that can be one of many cards in the view. One would expect the dropdown to just open over the top of the other elements on the page, including its parent element. As it stands, this is effectively preventing us from using the select dropdown.

@scomea has done some explorations here and I posted in our discord today that @radium-v has been iterating on adding this to select/combobox and likely will have something up in the next day or so. Landing the desired path here for our Foundation approach is a key part of our current alpha state of Foundation. Whatever is the default approach, we plan to enable users to take control or opt-out of the behavior if need be as well. The ultimately goal is a good default with the flexibility to customize for unique scenarios.

**Comment by thinkbig1979** [comment] 2022-10-13 06:40
Thanks @scomea and @chrisdholt. Great to see progress on this :-)

**Comment by rodesfl** [comment] 2024-04-24 10:36
Hey guys, just wondering if there was any progress on this ?

**Comment by chrisdholt** [comment] 2024-04-24 15:28
> Hey guys, just wondering if there was any progress on this ?

It's fixed in the latest beta - unfortunately I see this is breaking so it's unlikely to be included in the current stable release.

**Comment by janechu** [comment] 2024-05-28 21:10
Unfortunately `@microsoft/fast-components` has been deprecated for some time and `@microsoft/fast-foundation` is in progress to be deprecated per #6955. If this issue needs to be address in Fluent UI for those components, please file it there.

**Closed by janechu** 2024-05-28 21:10 UTC
Labels: bug, status:needs-investigation, area:fast-components
