### ISSUE TITLE
Several components broken in fast-components-msft v1.5.0

### ISSUE THREAD

**Issue by limefrogyank** [microsoft/fast#3529] opened 2020-07-18 19:44 UTC
I'm using Blazor.  Using v1.5 of fast-components-msft displays several components incorrectly:  

- Checkbox won't display the box.
- Slider won't show the bar
- Text-field won't show the outline box.

![image](https://user-images.githubusercontent.com/7821384/87860616-a7708a00-c8f3-11ea-9911-3fb9d421a353.png)

If I switch to v1.4, those visuals are good:
![image](https://user-images.githubusercontent.com/7821384/87860640-e69edb00-c8f3-11ea-8d21-d5b7da56e092.png)

I don't believe it is the fluent design package's fault because if you switch to the default, you can still see the same problems.  In fact, while your component explorer is working, the API page doesn't show the component correctly.  Here's checkbox:
https://fast.design/docs/components/checkbox

**In what environment did you see the issue?**

* OS & Device: Windows10 (not insider, but latest)
* Browser Edge
* Version 83.0.478.64

**Is there any additional context?**

**Comment by SayusiAndo** [comment] 2020-07-18 20:04
Possibly a duplicate of [3526](https://github.com/microsoft/fast/issues/3526#issuecomment-660298938)

**Comment by chrisdholt** [comment] 2020-07-18 20:12
Believe this is a dupe of 3526. Leaving open for tracking and will close if confirmed.

**Comment by chrisdholt** [comment] 2020-07-23 16:58
This appears to be resolved for the v1.6.0 CDN bundle via #3524: `https://unpkg.com/@microsoft/fast-components@1.6.0/dist/fast-components.min.js`

**Closed by chrisdholt** 2020-07-23 16:58 UTC
Labels: area:dev-ops, bug, status:in-progress

**Comment by limefrogyank** [comment] 2020-07-23 17:22
Yes, works fine now.  Thanks!
