### ISSUE TITLE
fix: Setting an element's attribute didn't always take effect

### ISSUE THREAD

**Issue by akronbook** [microsoft/fast#5480] opened 2021-12-17 06:19 UTC
# 🐛 Bug Report

When updating an element's attribute, the attribute didn't always take effect

## 💻 Repro or Code Sample

https://github.com/akronbook/fast-binding-bug

## 🤔 Expected Behavior

When updating an element's attribute, the attribute should always be updated to the specified value

## 😯 Current Behavior
In the sample code, I identified two approaches to replicate the bug. 
With the first approach, I set the default attribute to 'none'. Right click on text will display a popup menu (which is correct), but when trying to set the attribute to 'none' again by clicking the menu, the popup menu didn't close (which is surprising).

With the second approach, I set the default attribute to 'hello world'. Right click on text will display a popup menu (which is correct). Clicking the menu will close the popup (correct again here). But when right clicking on the text again, the menu will stay open no matter how many attempts to try to close it. In other words, setting the attribute to 'none' didn't take effect at all. You can use a browser's debugger and easily verify that the menu's attribute didn't change to 'none'.

## 💁 Possible Solution
No solutions so far.

## 🔦 Context
I am trying to build a simple context menu in a sample application, but was surprised that the context menu stays open.

## 🌍 Your Environment
* OS & Device: MacOS
* Browser: Chrome
* Version: @microsoft/fast-components 2.16.8, @microsoft/fast-element 1.6.2

**Comment by EisenbergEffect** [comment] 2021-12-18 02:36
Closing this since it's not a bug but an attempt to use two way binding which isn't yet a feature of FAST.

**Closed by EisenbergEffect** 2021-12-18 02:36 UTC
Labels: closed:not-actionable

**Comment by chrisdholt** [comment] 2021-12-18 02:37
> Closing this since it's not a bug but an attempt to use two way binding which isn't yet a feature of FAST.

YET 🥳
