### ISSUE TITLE
Slider animation pauses and restarts when arrow key held down

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3803] opened 2020-08-27 19:57 UTC
The slider animation pauses and restarts when arrow key is held down which seems odd.  A continuous animation would likely be better. 

Example:

Go to a page with a FAST slider with multiple steps (ie. the development slider samples).  
Focus on the thumb.  
Press and hold an arrow key
Note that slider thumb animates, pauses, then animates to the end.

**What behavior did you expect?**
A continuous animation.

**Comment by EisenbergEffect** [comment] 2020-09-09 15:42
@marjonlynch Are you presently working on this and expecting to get a PR in today or should we move this out to the next release? I saw that you self-assigned but that it was still in the backlog so I wasn't sure the statuc.

**Comment by nicholasrice** [comment] 2020-09-22 17:34
This is a tricky one because the platform is imposing a delay between the first keydown event emission and subsequent rapid keydown event emissions:

**Event cadence when holding down the arrow key**
e-------e-e-e-e-e-e-e-e-e-e-e-e...

I'm unsure what a fix for this would even be other than some transition timing coordination where the initial transition is faster? I'd be concerned that would be sensitive to machine performance characteristics. Happy to hear other ideas if anyone has them though.

FWIW the native range input has a similar behavior (though it does not transition): https://codesandbox.io/s/nervous-feistel-2cnuh?file=/index.html.

I'm inclined to close this as **by design** because it matches platform behavior and the above solution would likely not comprehensively fix the issue.

**Comment by scomea** [comment] 2020-09-23 17:51
I was looking at the React slider and it does have the same behavior, but doesn't seem as perceptibly I think because the transition looks to be a bit longer so it doesn't sit as long?

**Comment by marjonlynch** [comment] 2020-09-23 19:32
I think we are going to close this "by design", discussed offline with Nick

**Closed** 2020-09-23 20:58 UTC
Labels: area:fast-components, bug
