### ISSUE TITLE
fast-slider value attribute does not update

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#4021] opened 2020-10-12 04:59 UTC
I'm trying to use the `fast-slider` and would like to use it's `value`. I've tried to add a handler to the `change` event. But it is never raised. See https://github.com/microsoft/fast/issues/4019

Thus instead I would like to use the `MutationObserver` to watch for attribute changes. But when I drag the slider and change it's `value`, the `value` attribute is unchanged. Instead the `aria-valuenow` attribute is changed.

#### Solution

Also change the `value` attribute.

#### Example

**Before Drag**

![image](https://user-images.githubusercontent.com/42288570/95706837-46d5bc80-0c58-11eb-9e1a-9fadbd26f759.png)

**After Drag**

![image](https://user-images.githubusercontent.com/42288570/95706896-6371f480-0c58-11eb-8b25-561d5676d326.png)

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
<body style="margin:0px">
    <fast-design-system-provider use-defaults style="height:100%;">
        <fast-slider style="width:200px" min="0" max="100" step="1" value="10"></fast-slider>
    </fast-design-system-provider>
</body></html>
```

#### Additional Context

Don't drag with developer tools open. It won't work due to another bug. https://github.com/microsoft/fast/issues/4020

**Comment by nicholasrice** [comment] 2020-10-26 23:51
The value *attribute* is not written for every change to the element's value *property*. This is by design and is consistent with the behavior of native `<input />` elements.

The `value` property is observable however, and you can subscribe to changes to the `value` property using the the [Observable](https://www.fast.design/docs/fast-element/observables-and-state#external-observation) API. Additionally, in general a `change` event will be evoked from an element when a new value is committed. When this happens will vary from component to component.

**Closed** 2020-10-26 23:51 UTC
Labels: area:fast-components, bug, community:request, status:needs-investigation
