### ISSUE TITLE
fix: right click on FAST components crash Chrome

### ISSUE THREAD

**Issue by m4thieulavoie** [microsoft/fast#4959] opened 2021-07-14 18:37 UTC
# 🐛 Bug Report

With the few last FAST versions, right clicking some components make Chrome crash. There's no way for us to track any stack trace or get any console log as Chrome just straight crashes. Note that I can't reproduce on neither Opera or Firefox. We also noted it does not happen on FAST demo website

## 💻 Repro or Code Sample

n/a

## 🤔 Expected Behavior

Right click works as expected

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by Ibrahimmaga** [comment] 2021-07-14 19:09
can you provide some screenshots since you can't reproduce them?

**Comment by m4thieulavoie** [comment] 2021-07-14 19:56
> can you provide some screenshots since you can't reproduce them?

Sure, here it is!
![image](https://user-images.githubusercontent.com/44816587/125684707-8c07d400-c980-4ee4-8e8f-ae26a03b7e9a.png)

**Comment by Ibrahimmaga** [comment] 2021-07-14 20:10
Thank you

**Comment by Ibrahimmaga** [comment] 2021-07-14 20:29
Error Code 5 is a Windows error code that appears when the user does not have sufficient permission to access the requested file or location. It appears when the software was denied access to a location for the purposes of saving, copying, opening, or loading files. This usually occurs when your Windows user account does not have administrative privileges or when you attempt to access a network location or folder that is protected by using Windows User Account Control security policies. This error can appear when you attempt to browse to a location, save a file, or download a file. This error may also appear when attempting to run the Check for Updates feature, which downloads an installer to update the software.

If you encounter Error Code 5, try the following:

Make certain you are logged into Windows with a user account that has permission to access the location. In the case of downloading any updates, you will need to make sure your user account has permission to save files to the software's installation folder (usually C:\Program Files (x86)\GoFiler Complete or a folder in C:\Program Files (x86) with the name of your software). If your user account does not have permission to access the location, contact your organization's IT department or run the process with elevated privileges.
Our support team can help you identify this issue but we cannot resolve it directly for you. This error usually indicates an environmental issue that your IT department would have to resolve.

I believe you need at least to have read access to Microsoft fast, let me double-check with @awentzel and @chrisdholt. We may need to add you to the fast contributor list.

**Comment by chrisdholt** [comment] 2021-07-14 21:08
> Error Code 5 is a Windows error code that appears when the user does not have sufficient permission to access the requested file or location. It appears when the software was denied access to a location for the purposes of saving, copying, opening, or loading files. This usually occurs when your Windows user account does not have administrative privileges or when you attempt to access a network location or folder that is protected by using Windows User Account Control security policies. This error can appear when you attempt to browse to a location, save a file, or download a file. This error may also appear when attempting to run the Check for Updates feature, which downloads an installer to update the software.
> 
> If you encounter Error Code 5, try the following:
> 
> Make certain you are logged into Windows with a user account that has permission to access the location. In the case of downloading any updates, you will need to make sure your user account has permission to save files to the software's installation folder (usually C:\Program Files (x86)\GoFiler Complete or a folder in C:\Program Files (x86) with the name of your software). If your user account does not have permission to access the location, contact your organization's IT department or run the process with elevated privileges.
> Our support team can help you identify this issue but we cannot resolve it directly for you. This error usually indicates an environmental issue that your IT department would have to resolve.
> 
> I believe you need at least to have read access to Microsoft fast, let me double-check with @awentzel and @chrisdholt. We may need to add you to the fast contributor list.

I think this is vastly different and unrelated to the above - I think the error is valid and sounds like an issue within Chromium somewhere, which doesn't seem to repro on Chromium Edge. We should work to repro this in an environment on Chrome and dig into what's potentially causing this, additionally we can look for updates made in Chromium that may have caused a regression of some sort. Again, I don't think this has anything to do with the above Windows error code.

**Comment by m4thieulavoie** [comment] 2021-07-15 11:49
> Error Code 5 is a Windows error code that appears when the user does not have sufficient permission to access the requested file or location. It appears when the software was denied access to a location for the purposes of saving, copying, opening, or loading files. This usually occurs when your Windows user account does not have administrative privileges or when you attempt to access a network location or folder that is protected by using Windows User Account Control security policies. This error can appear when you attempt to browse to a location, save a file, or download a file. This error may also appear when attempting to run the Check for Updates feature, which downloads an installer to update the software.
> 
> If you encounter Error Code 5, try the following:
> 
> Make certain you are logged into Windows with a user account that has permission to access the location. In the case of downloading any updates, you will need to make sure your user account has permission to save files to the software's installation folder (usually C:\Program Files (x86)\GoFiler Complete or a folder in C:\Program Files (x86) with the name of your software). If your user account does not have permission to access the location, contact your organization's IT department or run the process with elevated privileges.
> Our support team can help you identify this issue but we cannot resolve it directly for you. This error usually indicates an environmental issue that your IT department would have to resolve.
> 
> I believe you need at least to have read access to Microsoft fast, let me double-check with @awentzel and @chrisdholt. We may need to add you to the fast contributor list.

I am on OSX, and this is way too random for it to be a permission issue (on top as we also experience this on prod). For example, if I click multiple times randomly on the page, the right click works as expected. However, refreshing and directly right-clicking a component crashes Chrome

**Comment by Ibrahimmaga** [comment] 2021-07-15 15:49
> > Error Code 5 is a Windows error code that appears when the user does not have sufficient permission to access the requested file or location. It appears when the software was denied access to a location for the purposes of saving, copying, opening, or loading files. This usually occurs when your Windows user account does not have administrative privileges or when you attempt to access a network location or folder that is protected by using Windows User Account Control security policies. This error can appear when you attempt to browse to a location, save a file, or download a file. This error may also appear when attempting to run the Check for Updates feature, which downloads an installer to update the software.
> > If you encounter Error Code 5, try the following:
> > Make certain you are logged into Windows with a user account that has permission to access the location. In the case of downloading any updates, you will need to make sure your user account has permission to save files to the software's installation folder (usually C:\Program Files (x86)\GoFiler Complete or a folder in C:\Program Files (x86) with the name of your software). If your user account does not have permission to access the location, contact your organization's IT department or run the process with elevated privileges.
> > Our support team can help you identify this issue but we cannot resolve it directly for you. This error usually indicates an environmental issue that your IT department would have to resolve.
> > I believe you need at least to have read access to Microsoft fast, let me double-check with @awentzel and @chrisdholt. We may need to add you to the fast contributor list.
> 
> I am on OSX, and this is way too random for it to be a permission issue (on top as we also experience this on prod). For example, if I click multiple times randomly on the page, the right click works as expected. However, refreshing and directly right-clicking a component crashes Chrome

>Hey @m4thieulavoie. Thanks for the feedback. I have verified with @awentzel that this is not a permission issue. So we are good there. And Christ confirmed that it is a chrome issue.  Here is a link that may help solve that issue on macOS with this type of error. Also, @chrisdholt may be a good resource. https://piunikaweb.com/2021/07/05/google-chrome-on-mac-aw-snap-error-5-when-opening-tabs-accessing-settings/

**Comment by CuddleBunny** [comment] 2021-07-15 15:56
I get a slightly different error page:

![image](https://user-images.githubusercontent.com/2207938/125818811-00b0884a-a43c-4b67-8bfc-b7810e2cadf7.png)

As mentioned above, I cannot recreate in the component explorer or even a [sandbox](https://codepen.io/CuddleBunny/pen/LYyWdoW). Perhaps it has something to do with events attached to the control? Perhaps even Blazor? You can recreate on one of my sites:

1. Navigate to [https://eservice.nationalgeneral.com/service](https://eservice.nationalgeneral.com/service) on Chrome
2. Enter any text in either login field
3. Highlight the text and attempt to right click it
4. ???
5. Crash

**Comment by chrisdholt** [comment] 2021-07-15 16:16
> I get a slightly different error page:
> 
> ![image](https://user-images.githubusercontent.com/2207938/125818811-00b0884a-a43c-4b67-8bfc-b7810e2cadf7.png)
> 
> As mentioned above, I cannot recreate in the component explorer or even a [sandbox](https://codepen.io/CuddleBunny/pen/LYyWdoW). Perhaps it has something to do with events attached to the control? Perhaps even Blazor? You can recreate on one of my sites:
> 
> 1. Navigate to https://eservice.nationalgeneral.com/service on Chrome
> 2. Enter any text in either login field
> 3. Highlight the text and attempt to right click it
> 4. ???
> 5. Crash

@CuddleBunny @m4thieulavoie I have a repro here, a few things on my plate today but will try and get deeper into an investigation here.

**Comment by CuddleBunny** [comment] 2022-01-07 17:37
@chrisdholt  It would seem this has been resolved on the Chrome end, I can no longer reproduce. @m4thieulavoie - are you still experiencing this issue?

**Comment by chrisdholt** [comment] 2022-01-07 19:10
> @chrisdholt It would seem this has been resolved on the Chrome end, I can no longer reproduce. @m4thieulavoie - are you still experiencing this issue?

Hopeful on this! Let us know @m4thieulavoie!

**Comment by m4thieulavoie** [comment] 2022-01-07 19:16
Unfortunately I am not working anymore at the company where we were experiencing the issue. If it's been fixed on the Chrome side and it hasn't been reported lately, I think it's safe to close the issue 👍

**Comment by chrisdholt** [comment] 2022-01-07 19:17
Closing per above! Thanks!

**Closed by chrisdholt** 2022-01-07 19:17 UTC
Labels: bug, status:in-progress, area:fast-components, community:request
