### ISSUE TITLE
fix: Radio button in your homepage

### ISSUE THREAD

**Issue by tiagocouto126** [microsoft/fast#6787] opened 2023-07-20 13:58 UTC
What: When I click "Radio 1" the one that gets checked is "Radio 2".
Where: in your homepage,
When: it seems that only in the first click ("radio group"), everytime I access the homepage. If already triggered the select of "Radio 2" then it "does not happen".

Windows 11
Chrome v 114.0.5735.199
Firefox Developer v 116.0b6

**Comment by olaf-k** [comment] 2023-12-06 14:43
dupe of #6687 and in general of #6735

**Comment by janechu** [comment] 2024-05-29 20:14
For the launch of v2 of `@microsoft/fast-element` we are completely redoing our homepage and it will not feature radio, closing this to reflect that upcoming change.

**Closed by janechu** 2024-05-29 20:14 UTC
Labels: bug, area:site
