### ISSUE TITLE
fix: clickhandler/indicator can't close dropdown list without selecting a option in combobox

### ISSUE THREAD

**Issue by SzymonZur** [microsoft/fast#5721] opened 2022-03-09 10:56 UTC
# 🐛 Bug Report

If you open a combobox, you simply can't close dropdown list without selecting a option. You only can pressing escape etc to close. 

## 💻 Repro or Code Sample

https://codesandbox.io/s/combobox-with-label-forked-e8mw3z?file=/index.html
1. Click the combobox. The combobox will open.
2. Try to close it by pressing indicator.

## 🤔 Expected Behavior

The combobox dropdown list should close by clicking indicator.

## 😯 Current Behavior

It stays open unless you pick an option or click escape etc.

## 💁 Possible Solution

Change clickHandler method to have more control on indicator (should open and close like "select" do).
Example:
https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-autocomplete-list.html

## 🌍 Your Environment

OS & Device: MacOS Monterey
Browser: Chrome
Version: fast-foundation "^2.16.0"

**Comment by EisenbergEffect** [comment] 2022-03-09 15:08
I'm not sure if this is a bug or by design, since the drop down closes when clicking off of the combobox. I've marked this as an improvement for now until @chrisdholt can chime in.

**Comment by chrisdholt** [comment] 2022-03-29 19:38
We're about to do a push on select issues (investigating/fixing/etc) - taking a look to validate what's expected. At worst clicking outside the control should likely collapse. Thanks for the issue!

**Comment by chrisdholt** [comment] 2022-04-29 05:43
After validating, both a light dismiss when clicking outside the control and clicking the indicator have recently been resolved in Open UI, so we'd be happy to pick this up.

**Comment by janechu** [comment] 2024-05-29 03:19
Unfortunately `@microsoft/fast-components` has been deprecated for some time.

**Closed by janechu** 2024-05-29 03:19 UTC
Labels: improvement, status:planned, area:fast-foundation, area:fast-components, community:request, task
