### ISSUE TITLE
feat: add events to files generated by CEM Analyzer

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#5863] opened 2022-04-18 15:55 UTC
# 🙋 Feature Request
I think it would be a useful addition to the CEM Analyzer script to add events emitted by a component to the generated API document.

## 🤔 Expected Behavior
Generated component API includes emitted events.

## 💁 Possible Solution
The `@custom-elements-manifest/analyzer` package already supports events via `@event` and `@fires` JSDoc directives.

## 🔦 Context
Currently it is a bit of a chore to find what events are emitted by a component. Not all of the component spec files list the events emitted by the component and ultimately you have to dig into the code to find it.

**Comment by EisenbergEffect** [comment] 2022-04-19 13:13
I believe this is planned. @williamw2 can provide more information or take feedback.

**Comment by KingOfTac** [comment] 2022-04-19 14:26
I also noticed that the name column doesn't populate for boolean attributes.

**Comment by williamw2** [comment] 2022-04-19 17:15
@KingOfTac - Yes, this is planned. I'm waiting on the Typescript version PR to be merged. Then I will need to upgrade our api-extractor and tsdoc-config version. After that I will be able to add all of the additional JSDOC tags supported by CEM Analyzer ("@event", "@slot", etc) to the tsdoc.json file and people can begin updating the components with this additional information.

**Comment by KingOfTac** [comment] 2022-04-19 17:18
Awesome, I can close this out then if needed.

**Comment by williamw2** [comment] 2022-04-19 17:29
You can leave it open. I'll close it once it is resolved. 

As for the blank names on boolean attributes, this is definitely a CEM Markdown quirk, and it appears to only be blank for attributes that have the same name as its field. For example, on Checkbox the "readonly" attribute name is different from the "readOnly" field name and it is displayed, but on Accordion the "expanded" attribute and field are the same and is omitted. I can investigate but I'm guessing this is an "as intended" feature of CEM Markdown. In the long run we plan to replace CEM Markdown with a custom generator which will give us much greater control over how this info is rendered.

**Comment by chrisdholt** [comment] 2022-05-05 03:20
closed with #5912

**Closed by chrisdholt** 2022-05-05 03:20 UTC
Labels: improvement, status:planned, area:fast-foundation, community:request
