### ISSUE TITLE
fast-text-area row, height, minlength and maxlength not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3874] opened 2020-09-10 07:44 UTC
I'm trying to wrap the fast-text-area into Bokeh extensions for use in Python and data science. Right now I'm working on the `fast-text-area` and there are some bugs (I believe).

I cannot get the following working

- minlength
- row
- height

A code example

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
<body style="margin:0px">
    <fast-design-system-provider use-defaults style="height:100%;">
        <fast-text-area
            rows="6"
            minlength="2"
            class="outline"
            resize="none"
            appearance="outline"
            style="height:400px">
                My Text
        </fast-text-area>
    </fast-design-system-provider>
</body></html>
```

looks like

![image](https://user-images.githubusercontent.com/42288570/92696221-da5e5980-f349-11ea-8201-80162861706d.png)

As you can see I can enter text with a length less than two and the height is fixed. It does not react to rows="6" or the `style="height:400px"` setting.

If you inspect the element you will find that the textarea control in the shadow dom has a fixed height.

![image](https://user-images.githubusercontent.com/42288570/92696408-1e515e80-f34a-11ea-9faf-6650aa73d635.png)

**Comment by MarcSkovMadsen** [comment] 2020-09-10 07:47
Furthermore the `maxlength` does not work as a property. But it works as an attribute.

![image](https://user-images.githubusercontent.com/42288570/92696649-75573380-f34a-11ea-8c7a-603921301b7d.png)

From the component explorer I would assume it should work as a property also

![image](https://user-images.githubusercontent.com/42288570/92696739-9b7cd380-f34a-11ea-8278-44601806e2da.png)

(My understanding is that the `Definition` defines the attributes and the `Schema` defines the properties?).

**Comment by chrisdholt** [comment] 2020-09-14 19:32
This looks related to #3869 though the issue is more clearcut. I'd expect this to also apply to `fast-text-field` and other inputs with this type of support. The issue here is relating the application of the attribute to the stylesheet. I think the best course of action would be to implement #3748 to get this supported. I'm not sure inline styles would work well here as it would require changes to fast-foundation and the text size, letter spacing, etc all seem to correlate to how one might calculate and apply these. Ultimately I think this would need be added on a per-design-system basis as it relates to specific styling stories.

**Comment by chrisdholt** [comment] 2022-04-16 23:02
I think we should close this given #5853, but I wanted to put together an example of how this could be accomplished using the design tokens. It's not perfect, but it is an approach that can support the concept and tends to work with smaller number sets...

Attaching a stackblitz where I've extended TextField and added a custom change handler for the maxlength attribute. I've created a design token and I am assigning that when maxlength changes. The tricky bit here is that while we can get close using `ch` and accounting for padding, `ch` doesn't give us the average character width. It is defined essentially as being equal to the measure of the “0” (ZERO, U+0030) found in the font being used. Example here: https://stackblitz.com/edit/typescript-9wblnv

I think you could likely do similar with other attributes as well.

**Closed** 2022-12-20 23:26 UTC
Labels: improvement, area:fast-components
