### ISSUE TITLE
Add shimmer state to components

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2255] opened 2019-09-19 20:40 UTC
**What feature are you requesting?**
Add support for displaying symbolic component boundaries in a shimmer state as data is loading. Requested by News.

**What would be the benefit of adding this feature?**
It provides a delightful placeholder that makes the page [feel like it's loading faster](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a).

**What solution would be ideal for you?**
[Fabric](https://developer.microsoft.com/en-us/fabric#/controls/web/shimmer) has a nice implementation. The speed is not too fast and the gradient is smooth and subtle.

In FAST terms, this would be based on the neutral palette. The animation is a linear gradient moving across the row. We would likely make this configurable, but the 0% and 100% of the gradient could start at 5 steps from the background. 50% at 8 steps.

Placeholder height should be based off of line height. Text would be capped to the max lines, otherwise 1 line. Components with a backplate would be represented as full height. Stealth components would be represented by line height.

**Attach screenshots or images add detail to your request:**
Here's an example from Fabric.
![image](https://user-images.githubusercontent.com/47367562/65279317-cbe8b380-dae2-11e9-88c2-9ca9bec0c8fa.png)
Notice that all three elements appear as one shimmer moving left to right.

**Comment by bheston** [comment] 2019-09-19 20:44
It would be nice if this were composable. That is, simple support at the base component level, with the ability to have something like a content card composed of multiple components appearing as the one logical item that it is, with the staggered shimmer as mentioned above.

Also, perhaps there's a way to attach this functionality through some sort of controller within a given context so it doesn't bloat places where it's not needed, and provides the opportunity to design the regions.

**Comment by EisenbergEffect** [comment] 2020-08-24 15:43
Closing as duplicate of #3755

**Comment by chrisdholt** [comment] 2020-11-21 03:18
Closing as this is "closed"

**Closed by chrisdholt** 2020-11-21 03:18 UTC
Labels: area:fast-components, closed:duplicate, feature
