### ISSUE TITLE
Data Grid goes out of focus on Tab

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4723] opened 2021-05-17 22:13 UTC
I have a Data Grid to render a dictionary. Each row is a Key Value Pair as shown below...

I select the first cell input and then hit tab, instead of focus going to the next text input element the entire data grid goes out of focus.

![image](https://user-images.githubusercontent.com/13166236/118562749-27d56680-b722-11eb-9f1b-4d60b302dd52.png)

Visual Studio 2019
Blazor Web Assembly

**Comment by ameyasubhedar** [comment] 2021-05-17 22:18
Also an extension of the issue, if the Data Grid itself has the focus then the next focus on Tab should go to the first fast component inside the data grid and then focus should then continue to next element in order.

![image](https://user-images.githubusercontent.com/13166236/118563264-193b7f00-b723-11eb-9f8f-6cb7c4c98e35.png)

**Comment by SethDonohue** [comment] 2021-05-18 18:36
This is the expected keyboard interaction pattern for Data Grids per the ARIA accessibility spec and for our Data Grid we have followed this pattern where the arrows keys are used to navigate through the Grid:
https://w3c.github.io/aria-practices/examples/grid/dataGrids.html

@scomea @chrisdholt I believe we can close this? Any other thoughts?

**Comment by scomea** [comment] 2021-05-18 21:58
Yes, the data grid should indeed be a single tab stop as per the Aria spec.  So that is by design.  There may be an issue with the grid being focused as in the image above though.  When the parent grid gets focus it should immediately throw it off to a focusable cell if there is one, and that doesn't look to be happening there. @ameyasubhedar - how is that grid created? are you passing it data or manually creating the rows?

**Comment by ameyasubhedar** [comment] 2021-05-18 22:29
@scomea Manually creating the row when user clicks the Add button in the image below.

**Comment by scomea** [comment] 2021-05-18 22:35
Ok, so I believe their is a bug here for "data grid does not autofocus on cells when rows are manually created".

**Comment by ameyasubhedar** [comment] 2021-05-19 03:14
Thanks updated the title so we can track the issue...

**Comment by scomea** [comment] 2021-05-24 22:29
Closed with https://github.com/microsoft/fast/pull/4740

**Closed by scomea** 2021-05-24 22:29 UTC
Labels: area:fast-components, bug, community:request, status:in-progress
