### ISSUE TITLE
fix: Accessibility within shadow root of icon button

### ISSUE THREAD

**Issue by rajsite** [microsoft/fast#5740] opened 2022-03-14 23:29 UTC
# 🐛 Bug Report

This is potentially more of a general shadow dom accessibility question / request for feedback on accessibility with shadow dom.

We are trying to make icon buttons and one thing we want to do for accessibility is to use slotted text as the aria label. The normal /  non-shadow dom equivalent based on `Technique #2: Accessible Visually Hidden Text with hidden and aria-labelledby` in [this article](https://www.sarasoueidan.com/blog/accessible-icon-buttons/) looks like:

```html
<button aria-labelledby="fromNormalDom">
  <span style="display: none" id="fromNormalDom"> Button Normal DOM </span>
</button>
```

Which in the accessibility tree view in Chrome renders as:
```
button "Button Normal DOM" focusable: true
```

Which is what we expect ✔

If I try to do the same concept with a shadow root in FAST (but don't think it's necessarily FAST related) I end up with the following in DOM:

```html
<my-element>
    #shadow-root (open)
        <button aria-labelledby="fromShadowDom">
            <span style="display: none" id="fromShadowDom"><slot></slot></span>
        </button>
    Button Shadow DOM
</my-element>
```

So note that the id of the span for the label and the button that receives the label are both in the shadow root. The id does not cross any boundary. The content is slotted into the slot of the span.

So conceptually I would expect the example to have the same accessibility tree as the normal DOM example. Both hide the text in the icon button but expect the button label to be applied from the hidden text.

However the chrome accessibility tree looks like:
```
button "" focusable: true
```

- Is this the expected behavior of a aria-labelledby inside a shadow root where the id does not cross any boundaries?

   The behavior I'm seeing feels like a bug in shadow dom that we are working around / we have some knowledge gap in shadow dom + accessibility we are missing.
- Do y'all have a pattern that would be recommended for this case instead?

    The `Technique #1: Accessible Visually Hidden Text` in [the above article](https://www.sarasoueidan.com/blog/accessible-icon-buttons/) is the approach we are looking at taking as a workaround. However, it definitely feels like a workaround to make things 1px by 1px and barely visible, etc. I don't mind as a short-term workaround but it doesn't feel like a long-term solution.

## 💻 Repro or Code Sample

https://stackblitz.com/edit/fast-accessible-slotted-content?file=index.html

## 🤔 Expected Behavior

aria-labelledby targeting an id within a shadow root works as expected

## 😯 Current Behavior

The aria-labelledby does not seem to work to target hidden text in a shadow root

## 💁 Possible Solution

Use Accessible Visually Hidden Text as a workaround.

## 🔦 Context

Creating an icon button

## 🌍 Your Environment

* Chrome 99
* Firefox 98
* NVDA 2021.3.1
* fast-element@1.8.0

**Comment by chrisdholt** [comment] 2022-03-14 23:33
Thanks @rajsite for this - triaging quickly but wanted to let you know that I'll dig in here and provide feedback

**Comment by chrisdholt** [comment] 2022-03-15 03:35
@rajsite can you try adding the following to your decorator where the element is being defined?

```ts
shadowOptions: {
    delegatesFocus: true,
}
```

**Comment by rajsite** [comment] 2022-03-15 04:18
> @rajsite can you try adding the following to your decorator where the element is being defined?
> 
> ```ts
> shadowOptions: {
>     delegatesFocus: true,
> }
> ```

Added an element definition `<my-element-delegates-focus>` to the stackblitz example with shadowOptions.delegatesFocus set to true. Our actual use-case had delegatesFocus set to true as well it was just overlooked in the minimal reproduction created in stackblitz. Has no change in behavior in the accessibility tree for chrome or firefox.

**Comment by chrisdholt** [comment] 2022-03-15 04:32
> > @rajsite can you try adding the following to your decorator where the element is being defined?
> > ```ts
> > shadowOptions: {
> >     delegatesFocus: true,
> > }
> > ```
> 
> Added an element definition `<my-element-delegates-focus>` to the stackblitz example with shadowOptions.delegatesFocus set to true. Our actual use-case had delegatesFocus set to true as well it was just overlooked in the minimal reproduction created in stackblitz. Has no change in behavior in the accessibility tree for chrome or firefox.

DOH! I just noticed what this is :) - https://stackblitz.com/edit/fast-accessible-slotted-content-vpfqfv?file=index.ts

In the example you're setting `display: none` on the span which uses the underlying `hidden` attribute which hides it from assistive technologies. You'll want to absolutely position the visual label offscreen.

**Comment by rajsite** [comment] 2022-03-15 04:35
@chrisdholt I added an additional example to the stackblitz with the `<my-element-no-slot>` where the slot where the text node is inserted is replaced with a span with a text node and the accessibility tree shows the button labelled correctly.

Makes me believe more strongly that it is a bug in the behavior of slotted nodes than with aria-labelledby in a shadow root. Also removed the icon from the stackblitz as it was cluttering the minimal example.

**Comment by chrisdholt** [comment] 2022-03-15 04:37
> @chrisdholt I added an additional example to the stackblitz with the `<my-element-no-slot>` where the slot where the text node is inserted is replaced with a span with a text node and the accessibility tree shows the button labelled correctly.
> 
> Makes me believe more strongly that it is a bug in the behavior of slotted nodes than with aria-labelledby in a shadow root. Also removed the icon from the stackblitz as it was cluttering the minimal example.

@rajsite I think you missed my update above a couple minutes ago :) 

Check out the example, I have it working as expected with that change. The issue is `display: none` on the label itself.

**Comment by rajsite** [comment] 2022-03-15 04:50
> > @chrisdholt I added an additional example to the stackblitz with the `<my-element-no-slot>` where the slot where the text node is inserted is replaced with a span with a text node and the accessibility tree shows the button labelled correctly.
> > Makes me believe more strongly that it is a bug in the behavior of slotted nodes than with aria-labelledby in a shadow root. Also removed the icon from the stackblitz as it was cluttering the minimal example.
> 
> @rajsite I think you missed my update above a couple minutes ago :)
> 
> Check out the example, I have it working as expected with that change. The issue is `display: none` on the label itself.

@chrisdholt what do you make of the latest update to the stackblitz where the slot doesn't work:
```ts
@customElement({
  name: 'my-element-delegates-focus',
  template: html<MyElementDelegatesFocus>`
    <button aria-labelledby="fromShadowDomDelegatesFocus">
      <span style="display: none" id="fromShadowDomDelegatesFocus"><slot></slot></span>
    </button>
  `,
  shadowOptions: {
    delegatesFocus: true,
  },
})
export class MyElementDelegatesFocus extends FASTElement {}
```

But swapping the slot with a hard-coded span still `display: none` does work:

```ts
@customElement({
  name: 'my-element-no-slot',
  template: html<MyElementNoSlot>`
    <button aria-labelledby="fromShadowDomNoSlot">
      <span style="display: none" id="fromShadowDomNoSlot"><span>Button Shadow DOM No Slot</span></span>
    </button>
  `,
  shadowOptions: {
    delegatesFocus: true,
  },
})
export class MyElementNoSlot extends FASTElement {}
```

> You'll want to absolutely position the visual label offscreen.

This isn't needed for the hard-coded span in the shadow root or for the normal html button example. It seems to only be necessary for slotted text nodes.

**Comment by chrisdholt** [comment] 2022-03-15 04:58
> > > @chrisdholt I added an additional example to the stackblitz with the `<my-element-no-slot>` where the slot where the text node is inserted is replaced with a span with a text node and the accessibility tree shows the button labelled correctly.
> > > Makes me believe more strongly that it is a bug in the behavior of slotted nodes than with aria-labelledby in a shadow root. Also removed the icon from the stackblitz as it was cluttering the minimal example.
> > 
> > 
> > @rajsite I think you missed my update above a couple minutes ago :)
> > Check out the example, I have it working as expected with that change. The issue is `display: none` on the label itself.
> 
> @chrisdholt what do you make of the latest update to the stackblitz where the slot doesn't work:
> 
> ```ts
> @customElement({
>   name: 'my-element-delegates-focus',
>   template: html<MyElementDelegatesFocus>`
>     <button aria-labelledby="fromShadowDomDelegatesFocus">
>       <span style="display: none" id="fromShadowDomDelegatesFocus"><slot></slot></span>
>     </button>
>   `,
>   shadowOptions: {
>     delegatesFocus: true,
>   },
> })
> export class MyElementDelegatesFocus extends FASTElement {}
> ```
> 
> But swapping the slot with a hard-coded span still `display: none` does work:
> 
> ```ts
> @customElement({
>   name: 'my-element-no-slot',
>   template: html<MyElementNoSlot>`
>     <button aria-labelledby="fromShadowDomNoSlot">
>       <span style="display: none" id="fromShadowDomNoSlot"><span>Button Shadow DOM No Slot</span></span>
>     </button>
>   `,
>   shadowOptions: {
>     delegatesFocus: true,
>   },
> })
> export class MyElementNoSlot extends FASTElement {}
> ```
> 
> > You'll want to absolutely position the visual label offscreen.
> 
> This isn't needed for the hard-coded span in the shadow root or for the normal html button example. It seems to only be necessary for slotted text nodes.

I can't speak to why the UIA tree is still representing it for the example above, but I can confidently say that the issue in the initial examples is absolutely the `display: none` from the light DOM. I can certainly look into whatwg and see if there's something purposeful or if it's a bug. It also could be NVDA trying to accommodate for legacy support or something like that. For reference on the `display: none;` issue:
- https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_none
- https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content
- https://webaim.org/techniques/css/invisiblecontent/#techniques

**Comment by rajsite** [comment] 2022-03-15 05:05
> > > > @chrisdholt I added an additional example to the stackblitz with the `<my-element-no-slot>` where the slot where the text node is inserted is replaced with a span with a text node and the accessibility tree shows the button labelled correctly.
> > > > Makes me believe more strongly that it is a bug in the behavior of slotted nodes than with aria-labelledby in a shadow root. Also removed the icon from the stackblitz as it was cluttering the minimal example.
> > > 
> > > 
> > > @rajsite I think you missed my update above a couple minutes ago :)
> > > Check out the example, I have it working as expected with that change. The issue is `display: none` on the label itself.
> > 
> > 
> > @chrisdholt what do you make of the latest update to the stackblitz where the slot doesn't work:
> > ```ts
> > @customElement({
> >   name: 'my-element-delegates-focus',
> >   template: html<MyElementDelegatesFocus>`
> >     <button aria-labelledby="fromShadowDomDelegatesFocus">
> >       <span style="display: none" id="fromShadowDomDelegatesFocus"><slot></slot></span>
> >     </button>
> >   `,
> >   shadowOptions: {
> >     delegatesFocus: true,
> >   },
> > })
> > export class MyElementDelegatesFocus extends FASTElement {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But swapping the slot with a hard-coded span still `display: none` does work:
> > ```ts
> > @customElement({
> >   name: 'my-element-no-slot',
> >   template: html<MyElementNoSlot>`
> >     <button aria-labelledby="fromShadowDomNoSlot">
> >       <span style="display: none" id="fromShadowDomNoSlot"><span>Button Shadow DOM No Slot</span></span>
> >     </button>
> >   `,
> >   shadowOptions: {
> >     delegatesFocus: true,
> >   },
> > })
> > export class MyElementNoSlot extends FASTElement {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > You'll want to absolutely position the visual label offscreen.
> > 
> > 
> > This isn't needed for the hard-coded span in the shadow root or for the normal html button example. It seems to only be necessary for slotted text nodes.
> 
> I can't speak to why the UIA tree is still representing it for the example above, but I can confidently say that the issue in the initial examples is absolutely the `display: none` from the light DOM. I can certainly look into whatwg and other standards to see if there's something purposeful or if it's a bug. It also could be NVDA trying to accommodate for legacy support or something like that. For reference on the `display: none;` issue:
> 
> * https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_none
> * https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content
> * https://webaim.org/techniques/css/invisiblecontent/#techniques

https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content

I think this article has a couple of quotes relevant here:

> Also, as we have seen, it's possible to provide screen reader only text via an aria-label, aria-labelledby, or aria-describedby attribute referencing an element that is otherwise hidden.
> 
> [...]
> 
> Finally, ARIA provides a mechanism for excluding content from assistive technology that is not visually hidden, using the aria-hidden attribute. Applying this attribute to an element effectively removes it and all of its descendants from the accessibility tree. The only exceptions are elements referred to by an aria-labelledby or aria-describedby attribute.

Which is what is happening in this case. We don't need the text itself visible, we are using it to label the button. My reading of that description makes me believe that you should be able to label the button with otherwise hidden elements.

**Comment by chrisdholt** [comment] 2022-03-15 05:08
> https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content
> 
> I think this article has a couple of quotes relevant here:
> 
> > Also, as we have seen, it's possible to provide screen reader only text via an aria-label, aria-labelledby, or aria-describedby attribute referencing an element that is otherwise hidden.
> > [...]
> > Finally, ARIA provides a mechanism for excluding content from assistive technology that is not visually hidden, using the aria-hidden attribute. Applying this attribute to an element effectively removes it and all of its descendants from the accessibility tree. The only exceptions are elements referred to by an aria-labelledby or aria-describedby attribute.
> 
> Which is what is happening in this case. We don't need the text itself visible, we are using it to label the button. My reading of that description makes me believe that you should be able to label the button with otherwise hidden elements.

I think that needs to be read in context and in light of the second paragraph of the article, which states that anything `display: none` or `visibility: hidden;` *will* be hidden from AT.

**Comment by rajsite** [comment] 2022-03-15 05:14
> > https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content
> > I think this article has a couple of quotes relevant here:
> > > Also, as we have seen, it's possible to provide screen reader only text via an aria-label, aria-labelledby, or aria-describedby attribute referencing an element that is otherwise hidden.
> > > [...]
> > > Finally, ARIA provides a mechanism for excluding content from assistive technology that is not visually hidden, using the aria-hidden attribute. Applying this attribute to an element effectively removes it and all of its descendants from the accessibility tree. The only exceptions are elements referred to by an aria-labelledby or aria-describedby attribute.
> > 
> > 
> > Which is what is happening in this case. We don't need the text itself visible, we are using it to label the button. My reading of that description makes me believe that you should be able to label the button with otherwise hidden elements.
> 
> I think that needs to be read in context and in light of the second paragraph of the article, which states that anything `display: none` or `visibility: hidden;` _will_ be hidden from AT.

The following example in the aria-labelledby documentation seems to indicate that elements targetted by aria-labelledby do not need to be in the accessibility tree: https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships#aria-labelledby

> You can use aria-labelledby to refer to elements that are hidden and would otherwise not be in the accessibility tree. For example, you could add a hidden span next to an element you want to label, and refer to that with aria-labelledby.

The MDN docs corroborate that statement: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby

> The aria-labelledby property value can include content from elements that aren't even visible. While you should provide assistive technology users with the same content and all other users, you can include content from elements with the HTML [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-hidden) attribute, CSS [display: none](https://developer.mozilla.org/en-US/docs/Web/CSS/display), and CSS [visibility: hidden](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility) in the calculated name string.

**Comment by chrisdholt** [comment] 2022-03-15 06:36
@rajsite, this is definitely interesting - and in digging in here, I don't think either of these are incorrect or in conflict, so I think you're correct that there is affordance for this. With that said, while I haven't found a reference for it yet, this seems specifically to do with how slot projection works. I'm going to close this as it pertains to the codebase as there's nothing actionable we can do here, but I'll see if I can find something that definitely provides the "rule". The outlier here is the slot though, which seems to make sense.

**Closed by chrisdholt** 2022-03-15 06:36 UTC
Labels: community:question, compliance:a11y, status:needs-author-input

**Comment by rajsite** [comment] 2022-03-15 16:30
@chrisdholt thanks for the discussion! We are going to go with "Accessible Visually Hidden Text" as the workaround similar to the stackblitz link you gave (seems to be broken now) and as proposed by the WebAIM article.

The PR we have in our code base is using a CSS Partial from the [Inclusively Hidden](https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html) article as follows:

```css
  clip: rect(0 0 0 0); 
  clip-path: inset(50%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap; 
  width: 1px;
```
 
Which is slightly different from the [WebAIM](https://webaim.org/techniques/css/invisiblecontent/#techniques) article suggestion of:

```css
clip: rect(1px, 1px, 1px, 1px);
clip-path: inset(50%);
height: 1px;
width: 1px;
margin: -1px;
overflow: hidden;
padding: 0;
position: absolute;
```

Mentioning in-case you have any existing insight on which workaround is more or less preferred.

I'll try and create an issue potentially on https://github.com/whatwg/html to see if there is expected behaviors with `<slot>`s exposing content for `aria-labelledby`. I'm vaguely aware of the AOM work being done for accessibility in web components so it may be of interest to hammer out.

**Comment by rajsite** [comment] 2024-02-22 17:06
@chrisdholt Interesting! I was looking into an issue in axe-core around aria labelling a component based on it's slotted content ([the section is labelled by slotted test](https://github.com/dequelabs/axe-core/issues/4335)) and remembered this issue.

I dunno when it was fixed, but now looking at the accessibility tree of the above [stackblitz](https://stackblitz.com/edit/fast-accessible-slotted-content?file=index.html), I can see in Firefox and Chrome that using a slot, even if the contents are hidden, works!

Chrome:
![image](https://github.com/microsoft/fast/assets/1588923/211d3a4e-0508-489d-9f61-607e37917fc7)

Firefox:
![image](https://github.com/microsoft/fast/assets/1588923/fcdbeb14-b96a-4675-abb6-e843c3a72d8b)

@EisenbergEffect that's one for the course (unless it's already in there), makes accessibility so much easier to be able to just point to a slot for the label.

Now to hope to the mac to try Safari.
