### ISSUE TITLE
rfc: What is the best default "contain" setting for the fast card component

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#4790] opened 2021-05-27 04:10 UTC
The fast card component has a default value of "content" for the css ["contain"](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) property.

While this may be the optimal value to enhance performance it has consequences that may not be immediately obvious to implementers, most notably that child flyouts (ie. dropdown menus, tooltips, etc....) that attempt to render outside of the boundaries of the card will be clipped.

Should we have a more permissive default setting for card that is less likely to seem broken (ie. "layout" or "none"), or should we stay with the current setting?

**Comment by UtmostCreator** [comment] 2021-05-27 10:48
It would be also nice to have it like in bootstrap:

```
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
  Tooltip on right
</button>
```

By this, I mean having these properties 
`data-toggle="tooltip" data-placement="right" title="Tooltip on right"`

we can set/see that this is a tooltip it has placement right and its text in the title attribute.


As for me, it is not really handy to set id for each element to add a tooltip it adds much more work + id as we know must be unique that only adds complexity

My points:
1. rewrite it so we can use it w/o id attribute (by giving more freedom to the devs);
2. add attributes for tooltip customization.

Attributes which I eager to see:
1. placement (top-start, top, top-end, left-start, left, left-end, right-start, right, right-end, bottom-start, bottom, bottom-end);
2. allow to inject html elements (like <em> <b> <u> <sub> <sup> <i>);
3. after a click it will be persistent until you click outside the tooltip (would be nice but not required from the very beginning);
4. font-size control;
5. tooltip color (font), background (color) dynamic as other fast elements;
6. it should work on disabled elements (if the property data-disabled-work="true", some sort of this thing);
7. other attributes which you may like can be found on [bootstrap page](https://getbootstrap.com/docs/4.0/components/tooltips/).

Hope it helps somehow for you to decide on what it would be nice to have.
I am open-minded, so please drop a comment below if you have any questions/suggestions.

**Comment by scomea** [comment] 2021-05-28 14:27
> Please let me know if I should create tooltip issue for this.

Yes, you should create a separate issue to discuss the idea of integrating tooltip in other components.  This discussion should be scoped to the "content" setting for cards.

**Comment by KingOfTac** [comment] 2021-06-04 20:25
An idea I have been mulling over is to possibly add a property to components to notify their ancestor if they are at risk of breaking it's containment e.g, `Tooltop.breaksContainment`, so `Card` can watch for and set the contain property via `DesignToken`. With something like this, containers can keep `contain: content` as the default and "smart" switch their containment if they contain at-risk elements.

Obviously there are possibly perf implications with containers walking through their entire tree to find elements that break containment, but I'm sure there are ways to make it performant. 

A possible solution to the perf issues is if a container's `contain` property is getting set from a `DesignToken` then descendants can set the value of the token on the container without the need for the container to walk its entire descendant tree.

**Comment by scomea** [comment] 2021-06-05 20:27
Hmm...I'd be wary of the performance cost of tree walking, but this got me thinking -  What if cards that didn't have an author set value for "contain" toggled to a more permissive value when they contained the document's active element?  It could be driven by focus events so wouldn't run a lot of code.  So basically the only card on the page that can could render flyouts outside its boundary would be the one that has focus.

**Comment by KingOfTac** [comment] 2021-06-05 22:46
Would this work with tooltips and hovering?

**Comment by scomea** [comment] 2021-06-06 15:29
No, you'd need to check for hovering too.

**Comment by KingOfTac** [comment] 2021-06-12 05:04
@scomea I've started playing around with your idea of driving the value of `contain` with events. I also want to look into capturing the behavior in a `CSSBehavior` for easy reuse, but I'm not super familiar with authoring behaviors so I don't know if it is even possible.

**Comment by scomea** [comment] 2021-06-13 17:09
Cool.  I think one checkbox would be being able to demonstrate that the mechanism doesn't disproportionately take away from the benefit of the more restrictive `contain` setting for a collection.  We'd need to come up with some way of evaluating that.

**Comment by chrisdholt** [comment] 2021-08-03 03:50
I love the conversation that's happening here and some of the various ideas for dynamic css properties. I'm not sure I've seen something that changes my mind in terms of "contain" being the right _default value_ for the base card `contain` property though. Cards typically represent smaller consumable "snapshots" of content, most often used in a group to present collections of related information. When we started building out `Card` and dug into the spec, we realized that while they are quite *common* across design systems, what goes in them vary significantly. Card is really a base building block for creating that piece of consumable content. It can be used as is, extended, restyled via CSS, etc...but I think the key is that it's a "good base".

Changing the `contain` value doesn't immediately fix some of the issues presented by the contain property. Elements do not naturally break out of their containers - that's most often achieved with CSS positioning and stacking context. Having that behavior work out of the box is going to be fairly difficult across all components as the concept of components breaking out of their parent is almost always contextual and NOT always desired. I've seen designs where content inside cards scroll, where that is a rigid boundary, or where things break out.  For many of the common use cases, the `<popup>` work being done in Open UI will bring that reality to the web platform and provide more OOTB support for this behavior, but as it is now, I'm not sure that I would expect to drop any given element into a card, or a dialog and have it immediately break out of its container. Certainly some make sense more than others - like a `...` menu we commonly see on cards, but I wouldn't say *every* menu or select, etc. Some of that still relies on implementation - for instance, I may dynamically insert a menu or tooltip into the DOM only when necessary and *outside* the actual card itself. The key for menus and tooltips is not the DOM structure but ensuring the relationship is tied w/ attributes for both sighted/non-sighted users. Given all this, I feel like contain is still relatively helpful and it's easy to override w/ CSS globally, per instance, etc. 

All that said, I'm still intrigued on the above. If we can apply a super lightweight utility to the card, I'm more than happy to take something like dynamic containment under consideration for the card. As it is right now, I think the risk is that we hoist a fairly expensive solution as a requirement for every instance, and that seems like a fairly big assumption. A behavior driven approach like @KingOfTac mentioned is super intriguing - I still wonder if that's better leveraged as part of an *implementation* of Card, but I'm certainly curious to see how light and adaptive that behavior can be - do I *have to* take it as a part of the base card or can it be opt-in?

**Comment by KingOfTac** [comment] 2021-08-03 05:44
This is something I keep coming back to when I get time. I've been  wanting to make a stacking context utility that components can use as a behavior but I haven't had much time lately. The idea is that when a popup or tooltip is triggered, if they are using the utility it will elevate their context to the top so they don't clip with other elements.

**Comment by chrisdholt** [comment] 2021-09-16 02:40
> I love the conversation that's happening here and some of the various ideas for dynamic css properties. I'm not sure I've seen something that changes my mind in terms of "contain" being the right _default value_ for the base card `contain` property though. Cards typically represent smaller consumable "snapshots" of content, most often used in a group to present collections of related information. When we started building out `Card` and dug into the spec, we realized that while they are quite _common_ across design systems, what goes in them vary significantly. Card is really a base building block for creating that piece of consumable content. It can be used as is, extended, restyled via CSS, etc...but I think the key is that it's a "good base".
> 
> Changing the `contain` value doesn't immediately fix some of the issues presented by the contain property. Elements do not naturally break out of their containers - that's most often achieved with CSS positioning and stacking context. Having that behavior work out of the box is going to be fairly difficult across all components as the concept of components breaking out of their parent is almost always contextual and NOT always desired. I've seen designs where content inside cards scroll, where that is a rigid boundary, or where things break out. For many of the common use cases, the `<popup>` work being done in Open UI will bring that reality to the web platform and provide more OOTB support for this behavior, but as it is now, I'm not sure that I would expect to drop any given element into a card, or a dialog and have it immediately break out of its container. Certainly some make sense more than others - like a `...` menu we commonly see on cards, but I wouldn't say _every_ menu or select, etc. Some of that still relies on implementation - for instance, I may dynamically insert a menu or tooltip into the DOM only when necessary and _outside_ the actual card itself. The key for menus and tooltips is not the DOM structure but ensuring the relationship is tied w/ attributes for both sighted/non-sighted users. Given all this, I feel like contain is still relatively helpful and it's easy to override w/ CSS globally, per instance, etc.
> 
> All that said, I'm still intrigued on the above. If we can apply a super lightweight utility to the card, I'm more than happy to take something like dynamic containment under consideration for the card. As it is right now, I think the risk is that we hoist a fairly expensive solution as a requirement for every instance, and that seems like a fairly big assumption. A behavior driven approach like @KingOfTac mentioned is super intriguing - I still wonder if that's better leveraged as part of an _implementation_ of Card, but I'm certainly curious to see how light and adaptive that behavior can be - do I _have to_ take it as a part of the base card or can it be opt-in?

Given the state of this issue, I'm going to close this for now as *by design* specifically for `card`. @KingofTac I'm still quite interested in seeing what you come up with and would definitely be interested in either pointing toward the behavior you create or taking it as a potential feature for `fast-foundation`. Please keep us up to date!

**Closed by chrisdholt** 2021-09-16 02:40 UTC
Labels: community:help-wanted, status:needs-investigation, area:fast-components, community:question

**Comment by KingOfTac** [comment] 2021-09-16 03:28
Will do. I haven't had a chance to revisit this in a while but it's on my list to work on by end the end of the month.

**Comment by KingOfTac** [comment] 2021-09-16 03:29
Will do. I haven't had a chance to revisit this in a while but it's on my list to work on by end the end of the month.
