### ISSUE TITLE
Select, Listbox, Combobox does not have label slots

### ISSUE THREAD

**Issue by apsthisdev** [microsoft/fast#4801] opened 2021-05-28 01:05 UTC
fast_select and fast_list and fast-combobox does not have label slot to show the title or the label .

E.g.

```
<fast-select>
    <label slot="label">Title</label>
    <fast-option value="1">Option 1</fast-option>
    <fast-option value="2">Option 2</fast-option>
    <fast-option value="3">Option 3</fast-option>
</fast-select>
```

![image](https://user-images.githubusercontent.com/13166236/119914763-d09b7700-bf15-11eb-8372-02cf1c2f07e6.png)

The fast_radio_group has the label slot and that helps to show the title.

```
<fast-radio-group>
    <label slot="label">Group label</label>
    <fast-radio>Radio label 1</fast-radio>
    <fast-radio>Radio label 2</fast-radio>
    <fast-radio>Radio label 3</fast-radio>
</fast-radio-group>

```
![image](https://user-images.githubusercontent.com/13166236/119914842-06d8f680-bf16-11eb-851f-d79af70cbc84.png)

**Comment by chrisdholt** [comment] 2021-05-28 01:11
Thanks for filing this issue @ameyasubhedar! I think this inconsistency should definitely be addressed. With that said, I'm not sure if the right fix is to *add* a label or *remove* the labels from some of the other form controls. One thing we are running in to right now is that certain (though not all) assistive technology is having trouble resolving the link between the light DOM slotted content for labels and the slot in the Shadow DOM. We're about to do a massive a11y audit as part of our June deliverables, and I think that will (hopefully) shed some clear light on the best path forward here.

**Comment by radium-v** [comment] 2021-06-01 21:32
Duplicate of #4642

**Comment by chrisdholt** [comment] 2022-04-16 21:39
To be picked up as part of Foundation vNext

**Comment by sseira** [comment] 2022-08-23 21:02
It would be great if there was an option to add the label inside the `.control` and sit above the `<slot name="button-container">`

Trying to create something like this - which is a pretty standard design direction

<img width="432" alt="image" src="https://user-images.githubusercontent.com/3791711/186264931-86b8aab5-61bd-4bd0-a99f-d3b8d67779b2.png">

**Comment by sseira** [comment] 2022-08-23 21:33
In case anyone is trying to achieve the same thing as me, I extended Select and overrode `displayValue()` to add a label and it seems to be working 
```
export class Select extends SelectFoundation {
  @attr
  label?: string

  /**
   * The value displayed on the button.
   *
   * @public
   */
  // @ts-ignore: Changing return type from string -> ViewTemplate to add label inside control
  public override get displayValue(): ViewTemplate {
    Observable.track(this, 'displayValue')
    return html`<div class="control-inner">
      ${this.label ? html`<label>${this.label}</label>` : ''}
      ${this.firstSelectedOption?.text}
    </div>`
  }
}
```

https://user-images.githubusercontent.com/3791711/186270292-d78e33df-6734-4546-902d-f4827d5ad059.mov

**Comment by janechu** [comment] 2024-05-28 21:11
Unfortunately `@microsoft/fast-components` has been deprecated for some time and `@microsoft/fast-foundation` is in process to be deprecated per #6955. I believe the Fluent UI web components will solve the issue in a different way as well for their v3 release.

**Closed by janechu** 2024-05-28 21:11 UTC
Labels: status:needs-investigation, area:fast-foundation, area:fast-components, community:request
