### ISSUE TITLE
fix: inappropriate foreground on accent hover in fast-component

### ISSUE THREAD

**Issue by fcollonval** [microsoft/fast#5587] opened 2022-02-10 11:30 UTC
# 🐛 Bug Report

Using some dynamic theming in light mode, I can have an accent color that results in foreground on accent hover being different (white instead of black) that other foreground on accent colors; see reproduction on fast design website below.

## 💻 Repro or Code Sample

![troublesome_accent_color](https://user-images.githubusercontent.com/8435071/153396835-30c3bacc-adf5-4e46-9ec3-3c40bd7a2cf5.gif)

The styles set on the node are:

```css
--accent-foreground-rest: #455cf0;
--accent-foreground-hover: #3a4ed2;
--accent-foreground-active: #5469f1;
--accent-foreground-focus: #455cf0;
--neutral-fill-rest: #ededed;
--neutral-fill-hover: #e5e5e5;
--neutral-fill-active: #f2f2f2;
--neutral-fill-focus: #ffffff;
--neutral-fill-input-rest: #ffffff;
--neutral-fill-input-hover: #ffffff;
--neutral-fill-input-active: #ffffff;
--neutral-fill-input-focus: #ffffff;
--neutral-fill-stealth-rest: #ffffff;
--neutral-fill-stealth-hover: #f2f2f2;
--neutral-fill-stealth-active: #f7f7f7;
--neutral-fill-stealth-focus: #ffffff;
--neutral-fill-strong-rest: #757575;
--neutral-fill-strong-hover: #616161;
--neutral-fill-strong-active: #828282;
--neutral-fill-strong-focus: #757575;
--neutral-fill-layer-rest: #f7f7f7;
--focus-stroke-inner: #fbfcff;
--focus-stroke-outer: #878787;
--neutral-foreground-hint: #757575;
--neutral-foreground-rest: #2b2b2b;
--neutral-stroke-rest: #bebebe;
--neutral-stroke-hover: #979797;
--neutral-stroke-active: #d5d5d5;
--neutral-stroke-focus: #bebebe;
--neutral-stroke-divider-rest: #eaeaea;
--tree-item-expand-collapse-hover: #e5e5e5;
--tree-item-expand-collapse-selected-hover: #e0e0e0;
--fill-color: #ffffff;
--neutral-layer-card-container: #f7f7f7;
--neutral-layer-floating: #ffffff;
--neutral-layer-1: #ffffff;
--neutral-layer-2: #e5e5e5;
--neutral-layer-3: #dddddd;
--neutral-layer-4: #d5d5d5;
--base-layer-luminance: 1;
--control-corner-radius: 3;
--accent-fill-rest: #5469f1;
--accent-fill-hover: #455cf0;
--accent-fill-active: #6779f3;
--accent-fill-focus: #5469f1;
--foreground-on-accent-active-large: #000000;
--foreground-on-accent-active: #000000;
--foreground-on-accent-rest: #000000;
--foreground-on-accent-focus: #000000;
```

Strangely `--foreground-on-accent-hover` is not set.

## 🤔 Expected Behavior

The foreground on accent hover does not change so drastically (black to white)

## 😯 Current Behavior

See above

## 🔦 Context

I'm working on [jupyter-ui-toolkit](https://github.com/jupyterlab-contrib/jupyter-ui-toolkit) in which I'm using CSS variable defined in the main application website to dynamically theme the components.

## 🌍 Your Environment

* OS & Device: Linux on PC
* Browser Mozilla FireFox
* Version 96.0.3

**Comment by bheston** [comment] 2022-04-15 00:10
This is tricky. The short answer is this is by design. This was changed in #4918, which includes some notes about why.

We know this behavior produces some cases like you found, though I tried to find the exact color you used and wasn't able to reproduce it now or find a color that produced this using the same UI. The competing issue is maintaining contrast in both rest and hover state combined with accurately keeping brand colors and allowing large deviations in background colors between states. All of which is possible through configuration of the system.

For the most flexibility, what we probably need is a recipe configuration where you can choose to maintain brand color or let the recipe adjust the background colors to maintain constant foreground color. Many configurations will do this by default, but the recipes need to be resilient which leads to less desirable edge cases like this.

**Comment by fcollonval** [comment] 2022-04-15 08:04
Thanks for the answer @bheston.

**Comment by chrisdholt** [comment] 2022-04-27 06:32
Closing as by design per the above answer from @bheston

**Closed by chrisdholt** 2022-04-27 06:32 UTC
Labels: bug, status:needs-investigation, area:fast-components, community:request
