### ISSUE TITLE
PureComponents: Please write ShouldComponentUpdate in Foundation

### ISSUE THREAD

**Issue by RohanMehta1** [microsoft/fast#766] opened 2018-08-07 21:00 UTC
**Describe the solution you'd like**
I am part of Microsoft News team and inheriting from Foundation class. We would like to suggest a lifecycle event addition in Foundation class. 

Kindly add ShouldComponentUpdate method by checking old and new props and determine if lifecycle should proceed with rendering or skip.

**Comment by chrisdholt** [comment] 2018-08-07 21:09
So, it sounds like the ask is to add functionality that would allow components to either opt-in (or opt-out) of "Pure Component" functionality.

I could envision this working in the following way:

- Foundation includes a default lifecycle method of "shouldComponentUpdate" which does a shallow compare of props to determine if the component should update. This would provide default functionality of components operating as "pure components"
- Foundation would include a "prop" or way of opting-out of the pure component functionality
- By design in React, if a user writes their own shouldComponentUpdate it will overwrite the default functionality *unless* they super the method.

@nicholasrice and @janechu - thoughts?

**Comment by nicholasrice** [comment] 2018-08-10 18:15
I'm on board with this proposal. 

It is a pretty big change in behavior, so I think this would qualify as a breaking change and should be targeted for a major release. Also, based on this article (https://medium.com/@antonkorzunov/2-things-about-purecomponent-you-probable-should-know-b04844a90d4) I think we need to complete #175 before making this change.

**Comment by chrisdholt** [comment] 2018-08-13 17:16
Blocked by #175

**Comment by chrisdholt** [comment] 2019-02-20 00:41
With the foundation component having *moved* into a new package, I think we can do this without causing a breaking change. Foundation includes a default export, which is *not* pure. We can add PureFoundation as a pure implementation of foundation which can be a named export. This would keep this change transparent. 

cc: @nicholasrice, @janechu

**Comment by nicholasrice** [comment] 2019-02-20 00:49
@chrisdholt sounds like a plan to me.

**Comment by nicholasrice** [comment] 2019-07-30 21:44
Closed by #1400

**Comment by chrisdholt** [comment] 2019-07-30 21:49
@nicholasrice that PR was closed/abandoned. I think we still need this it just hasn’t been a priority. Reopening unless there is a reason to not have this functionality.

**Comment by nicholasrice** [comment] 2019-07-30 21:52
Oh gotcha - cool, was wondering why the auto-close didn't work.

**Comment by Shpool** [comment] 2019-07-30 23:26
+1  for this functionality. We have bunch of different components on the project which require that. For now we just doing our custom shallow compare in ShouldComponentUpdate.

**Comment by chrisdholt** [comment] 2019-11-19 22:01
PR's welcome for those interested in contributing 👍

**Comment by chrisdholt** [comment] 2020-07-20 20:55
closed with #3517

**Closed by chrisdholt** 2020-07-20 20:55 UTC
Labels: area:react
