### ISSUE TITLE
Observables not binding to custom FAST Element properties when undefined [fast-element]

### ISSUE THREAD

**Issue by tgoze** [microsoft/fast#3820] opened 2020-08-28 18:03 UTC
Observables are not bound to custom element properties when initially undefined.

When defining an `observable` in an object or FAST Element and binding it to another FAST Element's property using the colon syntax, the other FAST Element will only receive updates from the observable if the observable is initialized with a value. If initially set to `undefined` the other element will not receive observable updates. See reproduction [here](https://webcomponents.dev/edit/971ChaOb26bGntGvcAbf?pm=1). 

To reproduce in the demo above:
1. Click 'See Test' and the value will print in the input as expected.
2. Change the initial value of the `outerValue` observable property on the `MyElement` class to an empty string. 
3. Click 'See Test' and the `MyChild` component will now update and show it's text.

Reproduced on Google Chrome v85.0.4183.83 and Microsoft Edge v85.0.564.41

**Comment by EisenbergEffect** [comment] 2020-12-07 17:28
@tgoze I believe this bug was fixed somewhere along the way. I can't reproduce it in your demo. The conditional rendering always updates correctly regardless of the starting value. One thing to note is that you probably want to bind the input's `value` attribute rather than the property, otherwise you'll get the string "undefined" displaying in your input control.

Here's a link the updated demo: https://webcomponents.dev/edit/971ChaOb26bGntGvcAbf?pm=1

Closing this for now as "obsolete". If I've misunderstood the problem, let me know and we can reopen.

**Closed by EisenbergEffect** 2020-12-07 17:28 UTC
Labels: area:fast-element, bug, community:request, status:needs-investigation

**Comment by tgoze** [comment] 2020-12-07 17:58
@EisenbergEffect Yes it looks like this has been fixed. Thanks!
