### ISSUE TITLE
fix: delegatesFocus breaks form submission with invalid required fields

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#5890] opened 2022-04-25 22:27 UTC
# 🐛 Bug Report

When submitting a form with an invalid required form component, an error is thrown.

## 💻 Repro or Code Sample

```html
<form action="#">
    <fast-combobox name="required-combobox" required>
        <fast-option>some option</fast-option>
    </fast-combobox>

    <fast-button type="submit">Submit</fast-button>
</form>
```

This affects these components:

* `<fast-combobox>`
* `<fast-number-field>`
* `<fast-search>`
* `<fast-text-area>`
* `<fast-text-field>`

## 🤔 Expected Behavior

When submitting the form with an empty value in a required field, the browser should focus the component and display a standard tooltip indicating that the field is required.

## 😯 Current Behavior

When submitting the form with an empty value in a required field, a console error is thrown by the browser:

```
An invalid form control with name='required-combobox' is not focusable.
```

## 💁 Possible Solution

This may be a web platform bug. Edge 100.0.1185.50 displays the error detailed above, but Firefox doesn't log any errors. Neither browser properly focuses the value-less component when the form submit button is clicked.

## 🔦 Context

Found while investigating #5839.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browsers: Microsoft Edge 100.0.1185.50, Google Chrome 100.0.4896.127, Mozilla Firefox 99.0.1

**Comment by derekdon** [comment] 2022-06-08 02:08
Just noticed this myself in Chrome Version 101.0.4951.64 (Official Build) (arm64) on mac.

**Comment by nicholasrice** [comment] 2022-08-10 22:34
This appears to be a dupe of #5678

**Closed by nicholasrice** 2022-08-10 22:34 UTC
Labels: bug, status:needs-investigation, area:fast-foundation
