### ISSUE TITLE
bug: publishing is failing do to beachball change folder in the master branch

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4712] opened 2021-05-13 16:50 UTC
# 🐛 Bug Report
Publishing is failing to beachball change folder in the master branch

## 💻 Repro or Code Sample
https://github.com/microsoft/fast/projects/31

## 🤔 Expected Behavior
Beachball change folder should be deleted automatically after the publish task

## 😯 Current Behavior
Each changed file that is being created is in the queue and never been deployed
![image](https://user-images.githubusercontent.com/14119043/118157078-f6c9fe80-b3ce-11eb-80f5-9094bab0e069.png)

## 💁 Possible Solution
1. Have a PR to delete from the change folder from master
2. always make sure to delete the change folder and create a new one after modifying a package
3. do a git pull master branch for the latest changes
4. deploy after a change file is ceated

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment] 2021-05-13 17:00
For clarity, is the change folder empty or does it include the change files? If we think this is an issue we should file it on Beachball rather than roll our own solution - doing so risks creating more issues in the future. Can we open something on Beachball rather than here if this is the case?

**Comment by Ibrahimmaga** [comment] 2021-05-13 17:18
The change folder includes new and old files which create a conflict. I think this is our issue rather than a beachball. we should look into a strategy for deploying first. I suggest a deployment on push so that the change folder gets deleted right away. but that just one solution.

**Comment by chrisdholt** [comment] 2021-05-13 17:22
> The change folder includes new and old files which create a conflict. I think this is our issue rather than a beachball. we should look into a strategy for deploying first. I suggest a deployment on push so that the change folder gets deleted right away. but that just one solution.

Are we sure that Beachball is not supposed to remove the change files? That’s been the behavior up until this point. Where is the code where we previously were doing this? I’m fairly certain that the change files in the change folder are supposed to be deleted as part of the publish process.

**Comment by Ibrahimmaga** [comment] 2021-05-13 17:46
Beachball always removes the change folder in master after a deployment. But in a workspace like visual studio code, it doesn't get deleted; which is normal.  You can resolve that by git pull master, and the change folder will no longer be there.  without git pull to reflect the change in master, the change folder ends up in the master again; this time it won't delete, but there will be an error on publish pipeline saying "This version was already been deployed".  and that also correct because we don't want to deploy the same version twice.

**Comment by awentzel** [comment] 2021-05-13 17:52
> Beachball always removes the change folder in master after a deployment. But in a workspace like visual studio code, it doesn't get deleted; which is normal. You can resolve that by git pull master, and the change folder will no longer be there. without git pull to reflect the change in master, the change folder ends up in the master again; this time it won't delete, but there will be an error on publish pipeline saying "This version was already been deployed". and that also correct because we don't want to deploy the same version twice.

This doesn't seem like a bug in the application.  This seems "by design" and ergonomics of the developer process.  Contributors should frequently be pulling down master and rebasing with their codebase and branches.  

@chrisdholt do you think otherwise?

**Comment by chrisdholt** [comment] 2021-05-13 17:56
> > Beachball always removes the change folder in master after a deployment. But in a workspace like visual studio code, it doesn't get deleted; which is normal. You can resolve that by git pull master, and the change folder will no longer be there. without git pull to reflect the change in master, the change folder ends up in the master again; this time it won't delete, but there will be an error on publish pipeline saying "This version was already been deployed". and that also correct because we don't want to deploy the same version twice.
> 
> This doesn't seem like a bug in the application. This seems "by design" and ergonomics of the developer process. Contributors should frequently be pulling down master and rebasing with their codebase and branches.
> 
> @chrisdholt do you think otherwise?

Yeah, I’m trying to grok the above - I wonder if this is due to clicking the merge button on Pr’s? What’s causing these to be reintroduced? Nobody should be pushing the master branch...and anything being added back in should go through code review. I see the files, I’m trying to figure out if they aren’t being deleted or when they are being added back in - and why it’s not showing up in reviews if that’s the case.

**Comment by awentzel** [comment] 2021-05-13 18:11
I'm attempting to re-sync the publish, which requires a force push, and then will monitor nightly, and if this happens again jump on it right away with a smaller sampling of what could be going wrong.

**Comment by Ibrahimmaga** [comment] 2021-05-13 22:10
Jane Chu — Today at 1:07 PM
Thanks for doing that chris!

Aaron Wentzel — Today at 1:13 PM
I'm stepping out for lunch, when I return and after this PR goes in I'll resume Publishing testing as well.  Thanksl

Chris Holt — Today at 2:42 PM
@Jane Chu @nicholasrice @Aaron Wentzel @EisenbergEffect sharing this here as it's currently on a couple threads. I think the issue we're running into is that Beachball is updating versions as part of publish - tooling is included in the current group, so it's expecting that the "right thing" to do is to update that when we publish new verisons of foundation, components, etc...it's basically swapping out "latest" for the new versions.

My assumption is that we need to exclude for the time being, specifically "fast-tooling" from the version group right now.
I need to jump out from this investigation, but we do need to resolve so long as the publish step is running and fast-tooling is pulling from NPM
Once we're back in "monorepo" mode, we should be good
I welcome thoughts

Aaron Wentzel — Today at 2:47 PM
Publishing is blocked until we're able to resolve.  If Jane's tooling approach is intended to always get latest then Chris's suggested solution makes sense.

Chris Holt — Today at 2:50 PM
Deets on "version groups": https://microsoft.github.io/beachball/concepts/groups.html
Version Groups | beachball
The Sunniest Semantic Version Bumper

Jane Chu — Today at 2:51 PM
I think if that works as a solution we can roll with it
my plan is to tackle tooling next week in the vNext branch and resolve any issues and re-pin the versions to their current mono-repo versions and away from latest

nicholasrice — Today at 2:54 PM
sorry I'm a little lost on your comment @Chris Holt. This is still in the context of the fixture issue? Does the above PR not resolve the beachball publish error?

Chris Holt — Today at 2:56 PM
All good - @nicholasrice the fixture issue PR exposed an issue related to beachball publishing. My build was failing because as part of the publish process, beachball syncs versions and pushes back to the master branch at origin. 

The fixture issue is fixed, however, we'll hit another build break I believe the next time tooling needs to publish.
nicholasrice — Today at 2:56 PM
oh lovely.

Chris Holt — Today at 2:57 PM
Beachball looks at things which should "version" together, which unless explicitly defined as excluded, it will assume all deps in the monorepo should version with local versions. So when it goes to bump and sync versions, it's changing latest to the monorepo version
Then the webpack alias fails because deps are hoisted and we're off to the races

nicholasrice — Today at 2:59 PM
ohhhh gotcha okay

**Comment by awentzel** [comment] 2021-05-13 22:23
We've identified this as a symptom of another problem that will be addressed in a future PR.

**Closed by awentzel** 2021-05-13 22:23 UTC
Labels: area:dev-ops, status:triage
