### ISSUE TITLE
docs: update expired SSL certificate in https://fast.design/docs/fast-element/getting-started

### ISSUE THREAD

**Issue by subratb** [microsoft/fast#6825] opened 2023-08-30 18:56 UTC
SSL Certificate has expired for [getting started](https://fast.design/docs/fast-element/getting-started) documentation.

**Comment by huynhicode** [comment] 2023-09-03 17:50
This is a duplicate of https://github.com/microsoft/fast/issues/6524.

**Closed** 2023-10-09 21:10 UTC
Labels: status:triage
