### ISSUE TITLE
fix: select component fails to display initially selected value

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#5425] opened 2021-11-30 23:15 UTC
# 🐛 Bug Report

When used in a data bound card component a user found that the value of an initially selected option was not being displayed.

## 💻 Repro or Code Sample

The component's template had a select with options that were bound to the components observable properties

        <fluent-select>
            <fluent-option selected>
                ${x => x.someValue}
          </fluent-option>
            <fluent-option>
                 ${x => x.someOtherValue}
            </fluent-option>
       </fluent-select>

With this markup the select did not display an initial value.  It appears that select identifies the initially selected option and attempts to grab its value before the binding has resolved.

## 🤔 Expected Behavior

Initial value displays.

## 😯 Current Behavior

Initially selected value does not display

**Comment by chrisdholt** [comment] 2021-11-30 23:18
Is this possibly a dupe of #5219 or #5220?

**Comment by scomea** [comment] 2021-11-30 23:41
> Is this possibly a dupe of #5219 or #5220?

Certainly in the same neighborhood as 5220, but different enough that it might not be the same fix.  Likely want to address together tho.

**Comment by chrisdholt** [comment] 2021-12-01 20:46
@radium-v can you investigate and add some context/thoughts here?

**Comment by scomea** [comment] 2021-12-01 21:02
Note: setting the displayValue property of the select to the initially selected value is a workaround. 
`:displayValue="${x => x.initialValue}"`

**Comment by radium-v** [comment] 2022-04-30 00:57
This may have been resolved by #5257

**Comment by chrisdholt** [comment] 2022-05-04 01:07
Just tried to repro and the above markup showed the correct default option when swapping between the option values. Closing this for now as fixed likely by #5257

**Closed by chrisdholt** 2022-05-04 01:07 UTC
Labels: bug, status:planned, area:fast-foundation, fast-components:final
