### ISSUE TITLE
feat: FAST vite template

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5409] opened 2021-11-19 15:08 UTC
# 🙋 Feature Request

For devs using vite, we should have both js and ts templates.

## 🤔 Expected Behavior

`npm init vite my-app --template fast` scaffolds out a FAST JS project with vite.
`npm init vite my-app --template fast-ts` scaffolds out a FAST TS project with vite.

## 😯 Current Behavior

No support out of the box.

## 💁 Possible Solution

Submit a PR here: https://github.com/vitejs/vite/tree/main/packages/create-vite
This would be similar to the way lit integrates.

**Comment by huynhicode** [comment] 2022-02-02 18:07
Closing this issue as it is a duplicate of https://github.com/microsoft/fast/issues/5260.

**Closed** 2022-06-22 14:03 UTC
Labels: feature, closed:done, area:tooling, community:request, community:noteworthy
