### ISSUE TITLE
fast_badge spacing changes inside a flex container

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4828] opened 2021-06-04 16:52 UTC
fast_badge spacing changes if it is inside a flex container.

**Without a flex container:**
![image](https://user-images.githubusercontent.com/13166236/120836436-6c327600-c51a-11eb-8f52-62c87f7b2026.png)

![image](https://user-images.githubusercontent.com/13166236/120836232-2e355200-c51a-11eb-9c76-c73c6558d694.png)

**With Flex container:**

![image](https://user-images.githubusercontent.com/13166236/120836373-5a50d300-c51a-11eb-8874-d00b549aea35.png)

![image](https://user-images.githubusercontent.com/13166236/120836023-f3331e80-c519-11eb-972a-f55e81b4cae3.png)

You can see the Badge1 Badge2 test are all next to each other without any spacing.

Why this inconsistency ?

**Comment by chrisdholt** [comment] 2021-06-04 20:28
From a component standpoint, we don't set spacing on the outside of components. Components are built as reusable parts which can be composed within other components or within an application. One of the issues with adding spacing to the outside of components is that it makes assumptions about the context the control is rendering into. Rather, our perspective is that when this is composed within another control, or when it is placed somewhere in the application, the positioning and margin is applied to the badge within that context. An example here would be a status badge on an avatar. While the badge in isolation has no spacing applied or positioning, when it's composed within the Avatar, that spacing and positioning (where it sits in relation to the Avatar is applied). Were we to apply that to the that status badge at its most basic level, any author using it in another way would need to override any conflicts with those assumptions being made with regard to spacing and positioning. For that reason, we don't set margin on components unless they are being used to compose a larger component or piece of UI. 

I think the above is part of what you're seeing, which is by design - but I also think that this is simply the behavior of how flexbox tends to work. Depending on your requirements, I see a few paths forward:

1) If you only need to support the most recent browser versions, `gap` should be available for Flexbox. If you need to support a few versions back, the below may be helpful.

2) Add margin via CSS to the badge's in the context of your UI using a class
```css
.my-dom-container {
   display: flex;
   justify-content: center;
   align-items: center;
}
   
// styles for badge inside your DOM container
// if these are direct children you can use the > selector
.my-dom-container fast-badge {
    margin-inline-end: 4px;
} 
```

3) Leverage css grid if possible instead of flexbox which has stronger support for things like `gap` in older versions of evergreen browsers

Hopefully some of these help. If you get stuck I'm happy to put together a small repro for you to check out. Closing this as by-design, but feel free to comment if you run into issues. Thanks!

**Closed by chrisdholt** 2021-06-04 20:28 UTC
Labels: status:triage
