### ISSUE TITLE
bug: focus disappears when tabbing through fast-menu items

### ISSUE THREAD

**Issue by stevenbenack** [microsoft/fast#4206] opened 2020-12-21 18:48 UTC
**Describe the bug; what happened?**
When tabbing through the fast foundation menu, focus gets lost. This is not an issue when using the up/down arrows, only when using tab.

**What are the steps to reproduce the issue?**

1. https://explore.fast.design/components/fast-menu
2. Attempt to tab through menu items
3. Observe that we are unable to tab through the items

**What behavior did you expect?**
The menu should allow for tab navigation of menu items.

**Comment by chrisdholt** [comment] 2020-12-21 20:39
Tabbing is not a valid method of navigation in a menu. Per the W3C, focus moves from item to item via arrow keys. The reason focus is disappearing is because focus is moving outside of the menu. Closing this as by design.

**Closed** 2020-12-21 20:39 UTC
Labels: closed:by-design, status:triage
