### ISSUE TITLE
Providing and resolving styles in FASTElement

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#3926] opened 2020-09-18 01:46 UTC
**Describe the bug; what happened?**

If you provide styles in `customElement` as well as respond to `resolveStyles`, only the latter are applied without warning or error. Looking at the code it looks like it only tries to apply resolved styles if provided styles are null.

**What are the steps to reproduce the issue?**

```ts
import { FASTElement, customElement, css, html } from "@microsoft/fast-element";

const template = html<TestStyles>`<div class="abc">
  <p>Hello</p>
</div>`;

const styles = css`
  .abc {
    background-color: green;
    font-weight: bold;
  }
`;

@customElement({
  name: "test-styles",
  template,
})
export class TestStyles extends FASTElement {
  resolveStyles() {
    return css`
      :host {
        background-color: blue;
      }
    `;
  }
}
```

**What behavior did you expect?**

Well, at first I expected only the styles passed to `customElement` to apply because I was coming back to the code and forgot about the `resolvedStyles`. Once I realized I looked at the code to try to understand the intent in this scenario, and it seemed like styles provided at the element took priority.

It might be good if they were merged. I would liked to keep the bulk of the styles in the recommended way, and provide a few that require custom code in resolved. Maybe that's too hard to merge though, so maybe I could inject the provided styles into the resolved. At the very least a warning or error in the console would have helped me realize my mistake much quicker.

**Comment by chrisdholt** [comment] 2020-09-18 04:00
I think what you're referencing would be accomplished with the proposed functionality in #3748. Can you take a look and see if that would support the behavior you are looking for?

**Comment by bheston** [comment] 2020-09-18 18:10
Yes, I recall seeing that proposal now and like the way it solves the problem. If by doing that we deprecate / remove `resolveStyles` I think that would solve the issue. If we maintain both for flexibility it would still be good to address the conflict in some way as suggested.

**Comment by chrisdholt** [comment] 2020-09-18 18:13
I'll let @eisenbergeffect chime in here, but I think resolveStyles is would be a replacement of and not supplemental to the style resolution in the decorator. I could be wrong here. If we were to implement #3748, I wouldn't expect to the above to also merge, but that's only an opinion.

**Comment by EisenbergEffect** [comment] 2020-09-18 19:16
By default an element gets its styles from the `styles` configured through the decorator. But, by implementing `resolveStyles` you can provide a custom algorithm by which to obtain the styles for the element. It's as an opt-in way to override the default mechanism for setting styles.

This is an enabler of the new provider model as the proposed `FoundationElement` would implement `resolveStyles` itself and use it to request the appropriate set of styles from the design system. In that new world, to specify styles for `fast-button` or `fluent-button` doesn't require inheritance or defining a new element. Rather, you just tell the design system "here are the styles for fast-button" and then when fast-button connects, its `resolveStyles` implementation asks the provider for the styles.

**Comment by EisenbergEffect** [comment] 2020-10-12 14:48
Closing as by design.

**Comment by chrisdholt** [comment] 2021-10-14 22:44
Closing officially per October 2020 Comment from @eisenbergeffect :)

**Closed by chrisdholt** 2021-10-14 22:44 UTC
Labels: closed:by-design, improvement, area:fast-element
