### ISSUE TITLE
Clicking fast-button forces browser reload in Safari 14

### ISSUE THREAD

**Issue by krs-10** [microsoft/fast#3947] opened 2020-09-22 19:31 UTC
**Describe the bug; what happened?**
Clicking on a `fast-button` in Safari 14 causes Safari to force-reload with the following error message: `This webpage was reloaded because a problem occurred.` The issue may be related to this ["delegatesFocus causes WebKit to crash" bug](https://bugs.webkit.org/show_bug.cgi?id=215622). 

**What are the steps to reproduce the issue?**

1. Go to https://fast.design/docs/components/button in Safari 14
2. Click on the "Submit" `fast-button` in the live editor preview result pane
3. See error

**What behavior did you expect?**
Interaction to match what happens on Chrome + FF

**If applicable, provide screenshots:**
![safari_14_fast_button_error](https://user-images.githubusercontent.com/33099338/93928618-97f13100-fce8-11ea-93b9-49de5711080b.gif)

**In what environment did you see the issue?**

* OS & Device: MacOS on 2018 MacBook Pro 
* Browser: Apple Safari
* Version: 14.0 (14610.1.28.1.9)

**Comment by EisenbergEffect** [comment] 2020-09-23 13:40
@krs-10 Thank you so much for linking the WebKit issue! We discovered the odd Safari behavior recently but hadn't yet tracked down the cause. I think this is likely it. 

@nicholasrice As we consider future strategies for form associated custom elements, might we opt to feature detect focus delegation and other features and branch how we *define* the element based on that? That would enable us to not specify focus delegation in the scenario that causes the WebKit bug. Maybe it's also a one-off fix for button/anchor as well. You would know much better than I 😄  Just want to make you aware since you are looking into similar issues.

/cc @awentzel

**Comment by EisenbergEffect** [comment] 2020-09-23 13:41
@nicholasrice Since this breaks our site in a major browser, do you think there's any quick fix we could get in for tomorrow's planned release?

**Comment by chrisdholt** [comment] 2020-09-23 16:08
@eisenbergeffect @nicholasrice please keep me in the loop here with what’s proposed as a temporary solution. Ideally this gets fixed ASAP by the WebKit team.

**Comment by EisenbergEffect** [comment] 2020-11-13 04:51
Looks like Big Sur fixes this. I'm installing now and will report back. The update is supposed to go to other versions of OSX as well, according to the webkit bug.

**Comment by EisenbergEffect** [comment] 2020-11-13 14:13
Ok, I have confirmed that this bug has been fixed by the webkit team and is now available. Closing as obsolete.

**Closed by EisenbergEffect** 2020-11-13 14:13 UTC
Labels: area:fast-components, browser:safari, bug, community:request, status:needs-investigation
